INSERT INTO districts(state,district) VALUES(Andhra PradeshAnantapur);
INSERT INTO districts(state,district) VALUES(Andhra PradeshChittoor);
INSERT INTO districts(state,district) VALUES(Andhra PradeshEast Godavari);
INSERT INTO districts(state,district) VALUES(Andhra PradeshGuntur);
INSERT INTO districts(state,district) VALUES(Andhra PradeshKrishna);
INSERT INTO districts(state,district) VALUES(Andhra PradeshKurnool);
INSERT INTO districts(state,district) VALUES(Andhra PradeshNellore);
INSERT INTO districts(state,district) VALUES(Andhra PradeshPrakasam);
INSERT INTO districts(state,district) VALUES(Andhra PradeshSrikakulam);
INSERT INTO districts(state,district) VALUES(Andhra PradeshVisakhapatnam);
INSERT INTO districts(state,district) VALUES(Andhra PradeshVizianagaram);
INSERT INTO districts(state,district) VALUES(Andhra PradeshWest Godavari);
INSERT INTO districts(state,district) VALUES(Andhra PradeshYSR Kadapa);
INSERT INTO districts(state,district) VALUES(Arunachal PradeshTawang);
INSERT INTO districts(state,district) VALUES(Arunachal PradeshWest Kameng);
INSERT INTO districts(state,district) VALUES(Arunachal PradeshEast Kameng);
INSERT INTO districts(state,district) VALUES(Arunachal PradeshPapum Pare);
INSERT INTO districts(state,district) VALUES(Arunachal PradeshKurung Kumey);
INSERT INTO districts(state,district) VALUES(Arunachal PradeshKra Daadi);
INSERT INTO districts(state,district) VALUES(Arunachal PradeshLower Subansiri);
INSERT INTO districts(state,district) VALUES(Arunachal PradeshUpper Subansiri);
INSERT INTO districts(state,district) VALUES(Arunachal PradeshWest Siang);
INSERT INTO districts(state,district) VALUES(Arunachal PradeshEast Siang);
INSERT INTO districts(state,district) VALUES(Arunachal PradeshSiang);
INSERT INTO districts(state,district) VALUES(Arunachal PradeshUpper Siang);
INSERT INTO districts(state,district) VALUES(Arunachal PradeshLower Siang);
INSERT INTO districts(state,district) VALUES(Arunachal PradeshLower Dibang Valley);
INSERT INTO districts(state,district) VALUES(Arunachal PradeshDibang Valley);
INSERT INTO districts(state,district) VALUES(Arunachal PradeshAnjaw);
INSERT INTO districts(state,district) VALUES(Arunachal PradeshLohit);
INSERT INTO districts(state,district) VALUES(Arunachal PradeshNamsai);
INSERT INTO districts(state,district) VALUES(Arunachal PradeshChanglang);
INSERT INTO districts(state,district) VALUES(Arunachal PradeshTirap);
INSERT INTO districts(state,district) VALUES(Arunachal PradeshLongding);
INSERT INTO districts(state,district) VALUES(AssamBaksa);
INSERT INTO districts(state,district) VALUES(AssamBarpeta);
INSERT INTO districts(state,district) VALUES(AssamBiswanath);
INSERT INTO districts(state,district) VALUES(AssamBongaigaon);
INSERT INTO districts(state,district) VALUES(AssamCachar);
INSERT INTO districts(state,district) VALUES(AssamCharaideo);
INSERT INTO districts(state,district) VALUES(AssamChirang);
INSERT INTO districts(state,district) VALUES(AssamDarrang);
INSERT INTO districts(state,district) VALUES(AssamDhemaji);
INSERT INTO districts(state,district) VALUES(AssamDhubri);
INSERT INTO districts(state,district) VALUES(AssamDibrugarh);
INSERT INTO districts(state,district) VALUES(AssamGoalpara);
INSERT INTO districts(state,district) VALUES(AssamGolaghat);
INSERT INTO districts(state,district) VALUES(AssamHailakandi);
INSERT INTO districts(state,district) VALUES(AssamHojai);
INSERT INTO districts(state,district) VALUES(AssamJorhat);
INSERT INTO districts(state,district) VALUES(AssamKamrup Metropolitan);
INSERT INTO districts(state,district) VALUES(AssamKamrup);
INSERT INTO districts(state,district) VALUES(AssamKarbi Anglong);
INSERT INTO districts(state,district) VALUES(AssamKarimganj);
INSERT INTO districts(state,district) VALUES(AssamKokrajhar);
INSERT INTO districts(state,district) VALUES(AssamLakhimpur);
INSERT INTO districts(state,district) VALUES(AssamMajuli);
INSERT INTO districts(state,district) VALUES(AssamMorigaon);
INSERT INTO districts(state,district) VALUES(AssamNagaon);
INSERT INTO districts(state,district) VALUES(AssamNalbari);
INSERT INTO districts(state,district) VALUES(AssamDima Hasao);
INSERT INTO districts(state,district) VALUES(AssamSivasagar);
INSERT INTO districts(state,district) VALUES(AssamSonitpur);
INSERT INTO districts(state,district) VALUES(AssamSouth Salmara-Mankachar);
INSERT INTO districts(state,district) VALUES(AssamTinsukia);
INSERT INTO districts(state,district) VALUES(AssamUdalguri);
INSERT INTO districts(state,district) VALUES(AssamWest Karbi Anglong);
INSERT INTO districts(state,district) VALUES(BiharAraria);
INSERT INTO districts(state,district) VALUES(BiharArwal);
INSERT INTO districts(state,district) VALUES(BiharAurangabad);
INSERT INTO districts(state,district) VALUES(BiharBanka);
INSERT INTO districts(state,district) VALUES(BiharBegusarai);
INSERT INTO districts(state,district) VALUES(BiharBhagalpur);
INSERT INTO districts(state,district) VALUES(BiharBhojpur);
INSERT INTO districts(state,district) VALUES(BiharBuxar);
INSERT INTO districts(state,district) VALUES(BiharDarbhanga);
INSERT INTO districts(state,district) VALUES(BiharEast Champaran (Motihari));
INSERT INTO districts(state,district) VALUES(BiharGaya);
INSERT INTO districts(state,district) VALUES(BiharGopalganj);
INSERT INTO districts(state,district) VALUES(BiharJamui);
INSERT INTO districts(state,district) VALUES(BiharJehanabad);
INSERT INTO districts(state,district) VALUES(BiharKaimur (Bhabua));
INSERT INTO districts(state,district) VALUES(BiharKatihar);
INSERT INTO districts(state,district) VALUES(BiharKhagaria);
INSERT INTO districts(state,district) VALUES(BiharKishanganj);
INSERT INTO districts(state,district) VALUES(BiharLakhisarai);
INSERT INTO districts(state,district) VALUES(BiharMadhepura);
INSERT INTO districts(state,district) VALUES(BiharMadhubani);
INSERT INTO districts(state,district) VALUES(BiharMunger (Monghyr));
INSERT INTO districts(state,district) VALUES(BiharMuzaffarpur);
INSERT INTO districts(state,district) VALUES(BiharNalanda);
INSERT INTO districts(state,district) VALUES(BiharNawada);
INSERT INTO districts(state,district) VALUES(BiharPatna);
INSERT INTO districts(state,district) VALUES(BiharPurnia (Purnea));
INSERT INTO districts(state,district) VALUES(BiharRohtas);
INSERT INTO districts(state,district) VALUES(BiharSaharsa);
INSERT INTO districts(state,district) VALUES(BiharSamastipur);
INSERT INTO districts(state,district) VALUES(BiharSaran);
INSERT INTO districts(state,district) VALUES(BiharSheikhpura);
INSERT INTO districts(state,district) VALUES(BiharSheohar);
INSERT INTO districts(state,district) VALUES(BiharSitamarhi);
INSERT INTO districts(state,district) VALUES(BiharSiwan);
INSERT INTO districts(state,district) VALUES(BiharSupaul);
INSERT INTO districts(state,district) VALUES(BiharVaishali);
INSERT INTO districts(state,district) VALUES(BiharWest Champaran);
INSERT INTO districts(state,district) VALUES(Chandigarh (UT)Chandigarh);
INSERT INTO districts(state,district) VALUES(ChhattisgarhBalod);
INSERT INTO districts(state,district) VALUES(ChhattisgarhBaloda Bazar);
INSERT INTO districts(state,district) VALUES(ChhattisgarhBalrampur);
INSERT INTO districts(state,district) VALUES(ChhattisgarhBastar);
INSERT INTO districts(state,district) VALUES(ChhattisgarhBemetara);
INSERT INTO districts(state,district) VALUES(ChhattisgarhBijapur);
INSERT INTO districts(state,district) VALUES(ChhattisgarhBilaspur);
INSERT INTO districts(state,district) VALUES(ChhattisgarhDantewada (South Bastar));
INSERT INTO districts(state,district) VALUES(ChhattisgarhDhamtari);
INSERT INTO districts(state,district) VALUES(ChhattisgarhDurg);
INSERT INTO districts(state,district) VALUES(ChhattisgarhGariyaband);
INSERT INTO districts(state,district) VALUES(ChhattisgarhJanjgir-Champa);
INSERT INTO districts(state,district) VALUES(ChhattisgarhJashpur);
INSERT INTO districts(state,district) VALUES(ChhattisgarhKabirdham (Kawardha));
INSERT INTO districts(state,district) VALUES(ChhattisgarhKanker (North Bastar));
INSERT INTO districts(state,district) VALUES(ChhattisgarhKondagaon);
INSERT INTO districts(state,district) VALUES(ChhattisgarhKorba);
INSERT INTO districts(state,district) VALUES(ChhattisgarhKorea (Koriya));
INSERT INTO districts(state,district) VALUES(ChhattisgarhMahasamund);
INSERT INTO districts(state,district) VALUES(ChhattisgarhMungeli);
INSERT INTO districts(state,district) VALUES(ChhattisgarhNarayanpur);
INSERT INTO districts(state,district) VALUES(ChhattisgarhRaigarh);
INSERT INTO districts(state,district) VALUES(ChhattisgarhRaipur);
INSERT INTO districts(state,district) VALUES(ChhattisgarhRajnandgaon);
INSERT INTO districts(state,district) VALUES(ChhattisgarhSukma);
INSERT INTO districts(state,district) VALUES(ChhattisgarhSurajpur  );
INSERT INTO districts(state,district) VALUES(ChhattisgarhSurguja);
INSERT INTO districts(state,district) VALUES(Dadra and Nagar Haveli (UT)Dadra & Nagar Haveli);
INSERT INTO districts(state,district) VALUES(Daman and Diu (UT)Daman);
INSERT INTO districts(state,district) VALUES(Daman and Diu (UT)Diu);
INSERT INTO districts(state,district) VALUES(Delhi (NCT)Central Delhi);
INSERT INTO districts(state,district) VALUES(Delhi (NCT)East Delhi);
INSERT INTO districts(state,district) VALUES(Delhi (NCT)New Delhi);
INSERT INTO districts(state,district) VALUES(Delhi (NCT)North Delhi);
INSERT INTO districts(state,district) VALUES(Delhi (NCT)North East  Delhi);
INSERT INTO districts(state,district) VALUES(Delhi (NCT)North West  Delhi);
INSERT INTO districts(state,district) VALUES(Delhi (NCT)Shahdara);
INSERT INTO districts(state,district) VALUES(Delhi (NCT)South Delhi);
INSERT INTO districts(state,district) VALUES(Delhi (NCT)South East Delhi);
INSERT INTO districts(state,district) VALUES(Delhi (NCT)South West  Delhi);
INSERT INTO districts(state,district) VALUES(Delhi (NCT)West Delhi);
INSERT INTO districts(state,district) VALUES(GoaNorth Goa);
INSERT INTO districts(state,district) VALUES(GoaSouth Goa);
INSERT INTO districts(state,district) VALUES(GujaratAhmedabad);
INSERT INTO districts(state,district) VALUES(GujaratAmreli);
INSERT INTO districts(state,district) VALUES(GujaratAnand);
INSERT INTO districts(state,district) VALUES(GujaratAravalli);
INSERT INTO districts(state,district) VALUES(GujaratBanaskantha (Palanpur));
INSERT INTO districts(state,district) VALUES(GujaratBharuch);
INSERT INTO districts(state,district) VALUES(GujaratBhavnagar);
INSERT INTO districts(state,district) VALUES(GujaratBotad);
INSERT INTO districts(state,district) VALUES(GujaratChhota Udepur);
INSERT INTO districts(state,district) VALUES(GujaratDahod);
INSERT INTO districts(state,district) VALUES(GujaratDangs (Ahwa));
INSERT INTO districts(state,district) VALUES(GujaratDevbhoomi Dwarka);
INSERT INTO districts(state,district) VALUES(GujaratGandhinagar);
INSERT INTO districts(state,district) VALUES(GujaratGir Somnath);
INSERT INTO districts(state,district) VALUES(GujaratJamnagar);
INSERT INTO districts(state,district) VALUES(GujaratJunagadh);
INSERT INTO districts(state,district) VALUES(GujaratKachchh);
INSERT INTO districts(state,district) VALUES(GujaratKheda (Nadiad));
INSERT INTO districts(state,district) VALUES(GujaratMahisagar);
INSERT INTO districts(state,district) VALUES(GujaratMehsana);
INSERT INTO districts(state,district) VALUES(GujaratMorbi);
INSERT INTO districts(state,district) VALUES(GujaratNarmada (Rajpipla));
INSERT INTO districts(state,district) VALUES(GujaratNavsari);
INSERT INTO districts(state,district) VALUES(GujaratPanchmahal (Godhra));
INSERT INTO districts(state,district) VALUES(GujaratPatan);
INSERT INTO districts(state,district) VALUES(GujaratPorbandar);
INSERT INTO districts(state,district) VALUES(GujaratRajkot);
INSERT INTO districts(state,district) VALUES(GujaratSabarkantha (Himmatnagar));
INSERT INTO districts(state,district) VALUES(GujaratSurat);
INSERT INTO districts(state,district) VALUES(GujaratSurendranagar);
INSERT INTO districts(state,district) VALUES(GujaratTapi (Vyara));
INSERT INTO districts(state,district) VALUES(GujaratVadodara);
INSERT INTO districts(state,district) VALUES(GujaratValsad);
INSERT INTO districts(state,district) VALUES(HaryanaAmbala);
INSERT INTO districts(state,district) VALUES(HaryanaBhiwani);
INSERT INTO districts(state,district) VALUES(HaryanaCharkhi Dadri);
INSERT INTO districts(state,district) VALUES(HaryanaFaridabad);
INSERT INTO districts(state,district) VALUES(HaryanaFatehabad);
INSERT INTO districts(state,district) VALUES(HaryanaGurgaon);
INSERT INTO districts(state,district) VALUES(HaryanaHisar);
INSERT INTO districts(state,district) VALUES(HaryanaJhajjar);
INSERT INTO districts(state,district) VALUES(HaryanaJind);
INSERT INTO districts(state,district) VALUES(HaryanaKaithal);
INSERT INTO districts(state,district) VALUES(HaryanaKarnal);
INSERT INTO districts(state,district) VALUES(HaryanaKurukshetra);
INSERT INTO districts(state,district) VALUES(HaryanaMahendragarh);
INSERT INTO districts(state,district) VALUES(HaryanaMewat);
INSERT INTO districts(state,district) VALUES(HaryanaPalwal);
INSERT INTO districts(state,district) VALUES(HaryanaPanchkula);
INSERT INTO districts(state,district) VALUES(HaryanaPanipat);
INSERT INTO districts(state,district) VALUES(HaryanaRewari);
INSERT INTO districts(state,district) VALUES(HaryanaRohtak);
INSERT INTO districts(state,district) VALUES(HaryanaSirsa);
INSERT INTO districts(state,district) VALUES(HaryanaSonipat);
INSERT INTO districts(state,district) VALUES(HaryanaYamunanagar);
INSERT INTO districts(state,district) VALUES(Himachal PradeshBilaspur);
INSERT INTO districts(state,district) VALUES(Himachal PradeshChamba);
INSERT INTO districts(state,district) VALUES(Himachal PradeshHamirpur);
INSERT INTO districts(state,district) VALUES(Himachal PradeshKangra);
INSERT INTO districts(state,district) VALUES(Himachal PradeshKinnaur);
INSERT INTO districts(state,district) VALUES(Himachal PradeshKullu);
INSERT INTO districts(state,district) VALUES(Himachal PradeshLahaul &amp; Spiti);
INSERT INTO districts(state,district) VALUES(Himachal PradeshMandi);
INSERT INTO districts(state,district) VALUES(Himachal PradeshShimla);
INSERT INTO districts(state,district) VALUES(Himachal PradeshSirmaur (Sirmour));
INSERT INTO districts(state,district) VALUES(Himachal PradeshSolan);
INSERT INTO districts(state,district) VALUES(Himachal PradeshUna);
INSERT INTO districts(state,district) VALUES(Jammu and KashmirAnantnag);
INSERT INTO districts(state,district) VALUES(Jammu and KashmirBandipore);
INSERT INTO districts(state,district) VALUES(Jammu and KashmirBaramulla);
INSERT INTO districts(state,district) VALUES(Jammu and KashmirBudgam);
INSERT INTO districts(state,district) VALUES(Jammu and KashmirDoda);
INSERT INTO districts(state,district) VALUES(Jammu and KashmirGanderbal);
INSERT INTO districts(state,district) VALUES(Jammu and KashmirJammu);
INSERT INTO districts(state,district) VALUES(Jammu and KashmirKargil);
INSERT INTO districts(state,district) VALUES(Jammu and KashmirKathua);
INSERT INTO districts(state,district) VALUES(Jammu and KashmirKishtwar);
INSERT INTO districts(state,district) VALUES(Jammu and KashmirKulgam);
INSERT INTO districts(state,district) VALUES(Jammu and KashmirKupwara);
INSERT INTO districts(state,district) VALUES(Jammu and KashmirLeh);
INSERT INTO districts(state,district) VALUES(Jammu and KashmirPoonch);
INSERT INTO districts(state,district) VALUES(Jammu and KashmirPulwama);
INSERT INTO districts(state,district) VALUES(Jammu and KashmirRajouri);
INSERT INTO districts(state,district) VALUES(Jammu and KashmirRamban);
INSERT INTO districts(state,district) VALUES(Jammu and KashmirReasi);
INSERT INTO districts(state,district) VALUES(Jammu and KashmirSamba);
INSERT INTO districts(state,district) VALUES(Jammu and KashmirShopian);
INSERT INTO districts(state,district) VALUES(Jammu and KashmirSrinagar);
INSERT INTO districts(state,district) VALUES(Jammu and KashmirUdhampur);
INSERT INTO districts(state,district) VALUES(JharkhandBokaro);
INSERT INTO districts(state,district) VALUES(JharkhandChatra);
INSERT INTO districts(state,district) VALUES(JharkhandDeoghar);
INSERT INTO districts(state,district) VALUES(JharkhandDhanbad);
INSERT INTO districts(state,district) VALUES(JharkhandDumka);
INSERT INTO districts(state,district) VALUES(JharkhandEast Singhbhum);
INSERT INTO districts(state,district) VALUES(JharkhandGarhwa);
INSERT INTO districts(state,district) VALUES(JharkhandGiridih);
INSERT INTO districts(state,district) VALUES(JharkhandGodda);
INSERT INTO districts(state,district) VALUES(JharkhandGumla);
INSERT INTO districts(state,district) VALUES(JharkhandHazaribag);
INSERT INTO districts(state,district) VALUES(JharkhandJamtara);
INSERT INTO districts(state,district) VALUES(JharkhandKhunti);
INSERT INTO districts(state,district) VALUES(JharkhandKoderma);
INSERT INTO districts(state,district) VALUES(JharkhandLatehar);
INSERT INTO districts(state,district) VALUES(JharkhandLohardaga);
INSERT INTO districts(state,district) VALUES(JharkhandPakur);
INSERT INTO districts(state,district) VALUES(JharkhandPalamu);
INSERT INTO districts(state,district) VALUES(JharkhandRamgarh);
INSERT INTO districts(state,district) VALUES(JharkhandRanchi);
INSERT INTO districts(state,district) VALUES(JharkhandSahibganj);
INSERT INTO districts(state,district) VALUES(JharkhandSeraikela-Kharsawan);
INSERT INTO districts(state,district) VALUES(JharkhandSimdega);
INSERT INTO districts(state,district) VALUES(JharkhandWest Singhbhum);
INSERT INTO districts(state,district) VALUES(KarnatakaBagalkot);
INSERT INTO districts(state,district) VALUES(KarnatakaBallari (Bellary));
INSERT INTO districts(state,district) VALUES(KarnatakaBelagavi (Belgaum));
INSERT INTO districts(state,district) VALUES(KarnatakaBengaluru (Bangalore) Rural);
INSERT INTO districts(state,district) VALUES(KarnatakaBengaluru (Bangalore) Urban);
INSERT INTO districts(state,district) VALUES(KarnatakaBidar);
INSERT INTO districts(state,district) VALUES(KarnatakaChamarajanagar);
INSERT INTO districts(state,district) VALUES(KarnatakaChikballapur);
INSERT INTO districts(state,district) VALUES(KarnatakaChikkamagaluru (Chikmagalur));
INSERT INTO districts(state,district) VALUES(KarnatakaChitradurga);
INSERT INTO districts(state,district) VALUES(KarnatakaDakshina Kannada);
INSERT INTO districts(state,district) VALUES(KarnatakaDavangere);
INSERT INTO districts(state,district) VALUES(KarnatakaDharwad);
INSERT INTO districts(state,district) VALUES(KarnatakaGadag);
INSERT INTO districts(state,district) VALUES(KarnatakaHassan);
INSERT INTO districts(state,district) VALUES(KarnatakaHaveri);
INSERT INTO districts(state,district) VALUES(KarnatakaKalaburagi (Gulbarga));
INSERT INTO districts(state,district) VALUES(KarnatakaKodagu);
INSERT INTO districts(state,district) VALUES(KarnatakaKolar);
INSERT INTO districts(state,district) VALUES(KarnatakaKoppal);
INSERT INTO districts(state,district) VALUES(KarnatakaMandya);
INSERT INTO districts(state,district) VALUES(KarnatakaMysuru (Mysore));
INSERT INTO districts(state,district) VALUES(KarnatakaRaichur);
INSERT INTO districts(state,district) VALUES(KarnatakaRamanagara);
INSERT INTO districts(state,district) VALUES(KarnatakaShivamogga (Shimoga));
INSERT INTO districts(state,district) VALUES(KarnatakaTumakuru (Tumkur));
INSERT INTO districts(state,district) VALUES(KarnatakaUdupi);
INSERT INTO districts(state,district) VALUES(KarnatakaUttara Kannada (Karwar));
INSERT INTO districts(state,district) VALUES(KarnatakaVijayapura (Bijapur));
INSERT INTO districts(state,district) VALUES(KarnatakaYadgir);
INSERT INTO districts(state,district) VALUES(KeralaAlappuzha);
INSERT INTO districts(state,district) VALUES(KeralaErnakulam);
INSERT INTO districts(state,district) VALUES(KeralaIdukki);
INSERT INTO districts(state,district) VALUES(KeralaKannur);
INSERT INTO districts(state,district) VALUES(KeralaKasaragod);
INSERT INTO districts(state,district) VALUES(KeralaKollam);
INSERT INTO districts(state,district) VALUES(KeralaKottayam);
INSERT INTO districts(state,district) VALUES(KeralaKozhikode);
INSERT INTO districts(state,district) VALUES(KeralaMalappuram);
INSERT INTO districts(state,district) VALUES(KeralaPalakkad);
INSERT INTO districts(state,district) VALUES(KeralaPathanamthitta);
INSERT INTO districts(state,district) VALUES(KeralaThiruvananthapuram);
INSERT INTO districts(state,district) VALUES(KeralaThrissur);
INSERT INTO districts(state,district) VALUES(KeralaWayanad);
INSERT INTO districts(state,district) VALUES(Lakshadweep (UT)Agatti);
INSERT INTO districts(state,district) VALUES(Lakshadweep (UT)Amini);
INSERT INTO districts(state,district) VALUES(Lakshadweep (UT)Androth);
INSERT INTO districts(state,district) VALUES(Lakshadweep (UT)Bithra);
INSERT INTO districts(state,district) VALUES(Lakshadweep (UT)Chethlath);
INSERT INTO districts(state,district) VALUES(Lakshadweep (UT)Kavaratti);
INSERT INTO districts(state,district) VALUES(Lakshadweep (UT)Kadmath);
INSERT INTO districts(state,district) VALUES(Lakshadweep (UT)Kalpeni);
INSERT INTO districts(state,district) VALUES(Lakshadweep (UT)Kilthan);
INSERT INTO districts(state,district) VALUES(Lakshadweep (UT)Minicoy);
INSERT INTO districts(state,district) VALUES(Madhya PradeshAgar Malwa);
INSERT INTO districts(state,district) VALUES(Madhya PradeshAlirajpur);
INSERT INTO districts(state,district) VALUES(Madhya PradeshAnuppur);
INSERT INTO districts(state,district) VALUES(Madhya PradeshAshoknagar);
INSERT INTO districts(state,district) VALUES(Madhya PradeshBalaghat);
INSERT INTO districts(state,district) VALUES(Madhya PradeshBarwani);
INSERT INTO districts(state,district) VALUES(Madhya PradeshBetul);
INSERT INTO districts(state,district) VALUES(Madhya PradeshBhind);
INSERT INTO districts(state,district) VALUES(Madhya PradeshBhopal);
INSERT INTO districts(state,district) VALUES(Madhya PradeshBurhanpur);
INSERT INTO districts(state,district) VALUES(Madhya PradeshChhatarpur);
INSERT INTO districts(state,district) VALUES(Madhya PradeshChhindwara);
INSERT INTO districts(state,district) VALUES(Madhya PradeshDamoh);
INSERT INTO districts(state,district) VALUES(Madhya PradeshDatia);
INSERT INTO districts(state,district) VALUES(Madhya PradeshDewas);
INSERT INTO districts(state,district) VALUES(Madhya PradeshDhar);
INSERT INTO districts(state,district) VALUES(Madhya PradeshDindori);
INSERT INTO districts(state,district) VALUES(Madhya PradeshGuna);
INSERT INTO districts(state,district) VALUES(Madhya PradeshGwalior);
INSERT INTO districts(state,district) VALUES(Madhya PradeshHarda);
INSERT INTO districts(state,district) VALUES(Madhya PradeshHoshangabad);
INSERT INTO districts(state,district) VALUES(Madhya PradeshIndore);
INSERT INTO districts(state,district) VALUES(Madhya PradeshJabalpur);
INSERT INTO districts(state,district) VALUES(Madhya PradeshJhabua);
INSERT INTO districts(state,district) VALUES(Madhya PradeshKatni);
INSERT INTO districts(state,district) VALUES(Madhya PradeshKhandwa);
INSERT INTO districts(state,district) VALUES(Madhya PradeshKhargone);
INSERT INTO districts(state,district) VALUES(Madhya PradeshMandla);
INSERT INTO districts(state,district) VALUES(Madhya PradeshMandsaur);
INSERT INTO districts(state,district) VALUES(Madhya PradeshMorena);
INSERT INTO districts(state,district) VALUES(Madhya PradeshNarsinghpur);
INSERT INTO districts(state,district) VALUES(Madhya PradeshNeemuch);
INSERT INTO districts(state,district) VALUES(Madhya PradeshPanna);
INSERT INTO districts(state,district) VALUES(Madhya PradeshRaisen);
INSERT INTO districts(state,district) VALUES(Madhya PradeshRajgarh);
INSERT INTO districts(state,district) VALUES(Madhya PradeshRatlam);
INSERT INTO districts(state,district) VALUES(Madhya PradeshRewa);
INSERT INTO districts(state,district) VALUES(Madhya PradeshSagar);
INSERT INTO districts(state,district) VALUES(Madhya PradeshSatna);
INSERT INTO districts(state,district) VALUES(Madhya PradeshSehore);
INSERT INTO districts(state,district) VALUES(Madhya PradeshSeoni);
INSERT INTO districts(state,district) VALUES(Madhya PradeshShahdol);
INSERT INTO districts(state,district) VALUES(Madhya PradeshShajapur);
INSERT INTO districts(state,district) VALUES(Madhya PradeshSheopur);
INSERT INTO districts(state,district) VALUES(Madhya PradeshShivpuri);
INSERT INTO districts(state,district) VALUES(Madhya PradeshSidhi);
INSERT INTO districts(state,district) VALUES(Madhya PradeshSingrauli);
INSERT INTO districts(state,district) VALUES(Madhya PradeshTikamgarh);
INSERT INTO districts(state,district) VALUES(Madhya PradeshUjjain);
INSERT INTO districts(state,district) VALUES(Madhya PradeshUmaria);
INSERT INTO districts(state,district) VALUES(Madhya PradeshVidisha);
INSERT INTO districts(state,district) VALUES(MaharashtraAhmednagar);
INSERT INTO districts(state,district) VALUES(MaharashtraAkola);
INSERT INTO districts(state,district) VALUES(MaharashtraAmravati);
INSERT INTO districts(state,district) VALUES(MaharashtraAurangabad);
INSERT INTO districts(state,district) VALUES(MaharashtraBeed);
INSERT INTO districts(state,district) VALUES(MaharashtraBhandara);
INSERT INTO districts(state,district) VALUES(MaharashtraBuldhana);
INSERT INTO districts(state,district) VALUES(MaharashtraChandrapur);
INSERT INTO districts(state,district) VALUES(MaharashtraDhule);
INSERT INTO districts(state,district) VALUES(MaharashtraGadchiroli);
INSERT INTO districts(state,district) VALUES(MaharashtraGondia);
INSERT INTO districts(state,district) VALUES(MaharashtraHingoli);
INSERT INTO districts(state,district) VALUES(MaharashtraJalgaon);
INSERT INTO districts(state,district) VALUES(MaharashtraJalna);
INSERT INTO districts(state,district) VALUES(MaharashtraKolhapur);
INSERT INTO districts(state,district) VALUES(MaharashtraLatur);
INSERT INTO districts(state,district) VALUES(MaharashtraMumbai City);
INSERT INTO districts(state,district) VALUES(MaharashtraMumbai Suburban);
INSERT INTO districts(state,district) VALUES(MaharashtraNagpur);
INSERT INTO districts(state,district) VALUES(MaharashtraNanded);
INSERT INTO districts(state,district) VALUES(MaharashtraNandurbar);
INSERT INTO districts(state,district) VALUES(MaharashtraNashik);
INSERT INTO districts(state,district) VALUES(MaharashtraOsmanabad);
INSERT INTO districts(state,district) VALUES(MaharashtraPalghar);
INSERT INTO districts(state,district) VALUES(MaharashtraParbhani);
INSERT INTO districts(state,district) VALUES(MaharashtraPune);
INSERT INTO districts(state,district) VALUES(MaharashtraRaigad);
INSERT INTO districts(state,district) VALUES(MaharashtraRatnagiri);
INSERT INTO districts(state,district) VALUES(MaharashtraSangli);
INSERT INTO districts(state,district) VALUES(MaharashtraSatara);
INSERT INTO districts(state,district) VALUES(MaharashtraSindhudurg);
INSERT INTO districts(state,district) VALUES(MaharashtraSolapur);
INSERT INTO districts(state,district) VALUES(MaharashtraThane);
INSERT INTO districts(state,district) VALUES(MaharashtraWardha);
INSERT INTO districts(state,district) VALUES(MaharashtraWashim);
INSERT INTO districts(state,district) VALUES(MaharashtraYavatmal);
INSERT INTO districts(state,district) VALUES(ManipurBishnupur);
INSERT INTO districts(state,district) VALUES(ManipurChandel);
INSERT INTO districts(state,district) VALUES(ManipurChurachandpur);
INSERT INTO districts(state,district) VALUES(ManipurImphal East);
INSERT INTO districts(state,district) VALUES(ManipurImphal West);
INSERT INTO districts(state,district) VALUES(ManipurJiribam);
INSERT INTO districts(state,district) VALUES(ManipurKakching);
INSERT INTO districts(state,district) VALUES(ManipurKamjong);
INSERT INTO districts(state,district) VALUES(ManipurKangpokpi);
INSERT INTO districts(state,district) VALUES(ManipurNoney);
INSERT INTO districts(state,district) VALUES(ManipurPherzawl);
INSERT INTO districts(state,district) VALUES(ManipurSenapati);
INSERT INTO districts(state,district) VALUES(ManipurTamenglong);
INSERT INTO districts(state,district) VALUES(ManipurTengnoupal);
INSERT INTO districts(state,district) VALUES(ManipurThoubal);
INSERT INTO districts(state,district) VALUES(ManipurUkhrul);
INSERT INTO districts(state,district) VALUES(MeghalayaEast Garo Hills);
INSERT INTO districts(state,district) VALUES(MeghalayaEast Jaintia Hills);
INSERT INTO districts(state,district) VALUES(MeghalayaEast Khasi Hills);
INSERT INTO districts(state,district) VALUES(MeghalayaNorth Garo Hills);
INSERT INTO districts(state,district) VALUES(MeghalayaRi Bhoi);
INSERT INTO districts(state,district) VALUES(MeghalayaSouth Garo Hills);
INSERT INTO districts(state,district) VALUES(MeghalayaSouth West Garo Hills );
INSERT INTO districts(state,district) VALUES(MeghalayaSouth West Khasi Hills);
INSERT INTO districts(state,district) VALUES(MeghalayaWest Garo Hills);
INSERT INTO districts(state,district) VALUES(MeghalayaWest Jaintia Hills);
INSERT INTO districts(state,district) VALUES(MeghalayaWest Khasi Hills);
INSERT INTO districts(state,district) VALUES(MizoramAizawl);
INSERT INTO districts(state,district) VALUES(MizoramChamphai);
INSERT INTO districts(state,district) VALUES(MizoramKolasib);
INSERT INTO districts(state,district) VALUES(MizoramLawngtlai);
INSERT INTO districts(state,district) VALUES(MizoramLunglei);
INSERT INTO districts(state,district) VALUES(MizoramMamit);
INSERT INTO districts(state,district) VALUES(MizoramSaiha);
INSERT INTO districts(state,district) VALUES(MizoramSerchhip);
INSERT INTO districts(state,district) VALUES(NagalandDimapur);
INSERT INTO districts(state,district) VALUES(NagalandKiphire);
INSERT INTO districts(state,district) VALUES(NagalandKohima);
INSERT INTO districts(state,district) VALUES(NagalandLongleng);
INSERT INTO districts(state,district) VALUES(NagalandMokokchung);
INSERT INTO districts(state,district) VALUES(NagalandMon);
INSERT INTO districts(state,district) VALUES(NagalandPeren);
INSERT INTO districts(state,district) VALUES(NagalandPhek);
INSERT INTO districts(state,district) VALUES(NagalandTuensang);
INSERT INTO districts(state,district) VALUES(NagalandWokha);
INSERT INTO districts(state,district) VALUES(NagalandZunheboto);
INSERT INTO districts(state,district) VALUES(OdishaAngul);
INSERT INTO districts(state,district) VALUES(OdishaBalangir);
INSERT INTO districts(state,district) VALUES(OdishaBalasore);
INSERT INTO districts(state,district) VALUES(OdishaBargarh);
INSERT INTO districts(state,district) VALUES(OdishaBhadrak);
INSERT INTO districts(state,district) VALUES(OdishaBoudh);
INSERT INTO districts(state,district) VALUES(OdishaCuttack);
INSERT INTO districts(state,district) VALUES(OdishaDeogarh);
INSERT INTO districts(state,district) VALUES(OdishaDhenkanal);
INSERT INTO districts(state,district) VALUES(OdishaGajapati);
INSERT INTO districts(state,district) VALUES(OdishaGanjam);
INSERT INTO districts(state,district) VALUES(OdishaJagatsinghapur);
INSERT INTO districts(state,district) VALUES(OdishaJajpur);
INSERT INTO districts(state,district) VALUES(OdishaJharsuguda);
INSERT INTO districts(state,district) VALUES(OdishaKalahandi);
INSERT INTO districts(state,district) VALUES(OdishaKandhamal);
INSERT INTO districts(state,district) VALUES(OdishaKendrapara);
INSERT INTO districts(state,district) VALUES(OdishaKendujhar (Keonjhar));
INSERT INTO districts(state,district) VALUES(OdishaKhordha);
INSERT INTO districts(state,district) VALUES(OdishaKoraput);
INSERT INTO districts(state,district) VALUES(OdishaMalkangiri);
INSERT INTO districts(state,district) VALUES(OdishaMayurbhanj);
INSERT INTO districts(state,district) VALUES(OdishaNabarangpur);
INSERT INTO districts(state,district) VALUES(OdishaNayagarh);
INSERT INTO districts(state,district) VALUES(OdishaNuapada);
INSERT INTO districts(state,district) VALUES(OdishaPuri);
INSERT INTO districts(state,district) VALUES(OdishaRayagada);
INSERT INTO districts(state,district) VALUES(OdishaSambalpur);
INSERT INTO districts(state,district) VALUES(OdishaSonepur);
INSERT INTO districts(state,district) VALUES(OdishaSundargarh);
INSERT INTO districts(state,district) VALUES(Puducherry (UT)Karaikal);
INSERT INTO districts(state,district) VALUES(Puducherry (UT)Mahe);
INSERT INTO districts(state,district) VALUES(Puducherry (UT)Pondicherry);
INSERT INTO districts(state,district) VALUES(Puducherry (UT)Yanam);
INSERT INTO districts(state,district) VALUES(PunjabAmritsar);
INSERT INTO districts(state,district) VALUES(PunjabBarnala);
INSERT INTO districts(state,district) VALUES(PunjabBathinda);
INSERT INTO districts(state,district) VALUES(PunjabFaridkot);
INSERT INTO districts(state,district) VALUES(PunjabFatehgarh Sahib);
INSERT INTO districts(state,district) VALUES(PunjabFazilka);
INSERT INTO districts(state,district) VALUES(PunjabFerozepur);
INSERT INTO districts(state,district) VALUES(PunjabGurdaspur);
INSERT INTO districts(state,district) VALUES(PunjabHoshiarpur);
INSERT INTO districts(state,district) VALUES(PunjabJalandhar);
INSERT INTO districts(state,district) VALUES(PunjabKapurthala);
INSERT INTO districts(state,district) VALUES(PunjabLudhiana);
INSERT INTO districts(state,district) VALUES(PunjabMansa);
INSERT INTO districts(state,district) VALUES(PunjabMoga);
INSERT INTO districts(state,district) VALUES(PunjabMuktsar);
INSERT INTO districts(state,district) VALUES(PunjabNawanshahr (Shahid Bhagat Singh Nagar));
INSERT INTO districts(state,district) VALUES(PunjabPathankot);
INSERT INTO districts(state,district) VALUES(PunjabPatiala);
INSERT INTO districts(state,district) VALUES(PunjabRupnagar);
INSERT INTO districts(state,district) VALUES(PunjabSahibzada Ajit Singh Nagar (Mohali));
INSERT INTO districts(state,district) VALUES(PunjabSangrur);
INSERT INTO districts(state,district) VALUES(PunjabTarn Taran);
INSERT INTO districts(state,district) VALUES(RajasthanAjmer);
INSERT INTO districts(state,district) VALUES(RajasthanAlwar);
INSERT INTO districts(state,district) VALUES(RajasthanBanswara);
INSERT INTO districts(state,district) VALUES(RajasthanBaran);
INSERT INTO districts(state,district) VALUES(RajasthanBarmer);
INSERT INTO districts(state,district) VALUES(RajasthanBharatpur);
INSERT INTO districts(state,district) VALUES(RajasthanBhilwara);
INSERT INTO districts(state,district) VALUES(RajasthanBikaner);
INSERT INTO districts(state,district) VALUES(RajasthanBundi);
INSERT INTO districts(state,district) VALUES(RajasthanChittorgarh);
INSERT INTO districts(state,district) VALUES(RajasthanChuru);
INSERT INTO districts(state,district) VALUES(RajasthanDausa);
INSERT INTO districts(state,district) VALUES(RajasthanDholpur);
INSERT INTO districts(state,district) VALUES(RajasthanDungarpur);
INSERT INTO districts(state,district) VALUES(RajasthanHanumangarh);
INSERT INTO districts(state,district) VALUES(RajasthanJaipur);
INSERT INTO districts(state,district) VALUES(RajasthanJaisalmer);
INSERT INTO districts(state,district) VALUES(RajasthanJalore);
INSERT INTO districts(state,district) VALUES(RajasthanJhalawar);
INSERT INTO districts(state,district) VALUES(RajasthanJhunjhunu);
INSERT INTO districts(state,district) VALUES(RajasthanJodhpur);
INSERT INTO districts(state,district) VALUES(RajasthanKarauli);
INSERT INTO districts(state,district) VALUES(RajasthanKota);
INSERT INTO districts(state,district) VALUES(RajasthanNagaur);
INSERT INTO districts(state,district) VALUES(RajasthanPali);
INSERT INTO districts(state,district) VALUES(RajasthanPratapgarh);
INSERT INTO districts(state,district) VALUES(RajasthanRajsamand);
INSERT INTO districts(state,district) VALUES(RajasthanSawai Madhopur);
INSERT INTO districts(state,district) VALUES(RajasthanSikar);
INSERT INTO districts(state,district) VALUES(RajasthanSirohi);
INSERT INTO districts(state,district) VALUES(RajasthanSri Ganganagar);
INSERT INTO districts(state,district) VALUES(RajasthanTonk);
INSERT INTO districts(state,district) VALUES(RajasthanUdaipur);
INSERT INTO districts(state,district) VALUES(SikkimEast Sikkim);
INSERT INTO districts(state,district) VALUES(SikkimNorth Sikkim);
INSERT INTO districts(state,district) VALUES(SikkimSouth Sikkim);
INSERT INTO districts(state,district) VALUES(SikkimWest Sikkim);
INSERT INTO districts(state,district) VALUES(Tamil NaduAriyalur);
INSERT INTO districts(state,district) VALUES(Tamil NaduChennai);
INSERT INTO districts(state,district) VALUES(Tamil NaduCoimbatore);
INSERT INTO districts(state,district) VALUES(Tamil NaduCuddalore);
INSERT INTO districts(state,district) VALUES(Tamil NaduDharmapuri);
INSERT INTO districts(state,district) VALUES(Tamil NaduDindigul);
INSERT INTO districts(state,district) VALUES(Tamil NaduErode);
INSERT INTO districts(state,district) VALUES(Tamil NaduKanchipuram);
INSERT INTO districts(state,district) VALUES(Tamil NaduKanyakumari);
INSERT INTO districts(state,district) VALUES(Tamil NaduKarur);
INSERT INTO districts(state,district) VALUES(Tamil NaduKrishnagiri);
INSERT INTO districts(state,district) VALUES(Tamil NaduMadurai);
INSERT INTO districts(state,district) VALUES(Tamil NaduNagapattinam);
INSERT INTO districts(state,district) VALUES(Tamil NaduNamakkal);
INSERT INTO districts(state,district) VALUES(Tamil NaduNilgiris);
INSERT INTO districts(state,district) VALUES(Tamil NaduPerambalur);
INSERT INTO districts(state,district) VALUES(Tamil NaduPudukkottai);
INSERT INTO districts(state,district) VALUES(Tamil NaduRamanathapuram);
INSERT INTO districts(state,district) VALUES(Tamil NaduSalem);
INSERT INTO districts(state,district) VALUES(Tamil NaduSivaganga);
INSERT INTO districts(state,district) VALUES(Tamil NaduThanjavur);
INSERT INTO districts(state,district) VALUES(Tamil NaduTheni);
INSERT INTO districts(state,district) VALUES(Tamil NaduThoothukudi (Tuticorin));
INSERT INTO districts(state,district) VALUES(Tamil NaduTiruchirappalli);
INSERT INTO districts(state,district) VALUES(Tamil NaduTirunelveli);
INSERT INTO districts(state,district) VALUES(Tamil NaduTiruppur);
INSERT INTO districts(state,district) VALUES(Tamil NaduTiruvallur);
INSERT INTO districts(state,district) VALUES(Tamil NaduTiruvannamalai);
INSERT INTO districts(state,district) VALUES(Tamil NaduTiruvarur);
INSERT INTO districts(state,district) VALUES(Tamil NaduVellore);
INSERT INTO districts(state,district) VALUES(Tamil NaduViluppuram);
INSERT INTO districts(state,district) VALUES(Tamil NaduVirudhunagar);
INSERT INTO districts(state,district) VALUES(TelanganaAdilabad);
INSERT INTO districts(state,district) VALUES(TelanganaBhadradri Kothagudem);
INSERT INTO districts(state,district) VALUES(TelanganaHyderabad);
INSERT INTO districts(state,district) VALUES(TelanganaJagtial);
INSERT INTO districts(state,district) VALUES(TelanganaJangaon);
INSERT INTO districts(state,district) VALUES(TelanganaJayashankar Bhoopalpally);
INSERT INTO districts(state,district) VALUES(TelanganaJogulamba Gadwal);
INSERT INTO districts(state,district) VALUES(TelanganaKamareddy);
INSERT INTO districts(state,district) VALUES(TelanganaKarimnagar);
INSERT INTO districts(state,district) VALUES(TelanganaKhammam);
INSERT INTO districts(state,district) VALUES(TelanganaKomaram Bheem Asifabad);
INSERT INTO districts(state,district) VALUES(TelanganaMahabubabad);
INSERT INTO districts(state,district) VALUES(TelanganaMahabubnagar);
INSERT INTO districts(state,district) VALUES(TelanganaMancherial);
INSERT INTO districts(state,district) VALUES(TelanganaMedak);
INSERT INTO districts(state,district) VALUES(TelanganaMedchal);
INSERT INTO districts(state,district) VALUES(TelanganaNagarkurnool);
INSERT INTO districts(state,district) VALUES(TelanganaNalgonda);
INSERT INTO districts(state,district) VALUES(TelanganaNirmal);
INSERT INTO districts(state,district) VALUES(TelanganaNizamabad);
INSERT INTO districts(state,district) VALUES(TelanganaPeddapalli);
INSERT INTO districts(state,district) VALUES(TelanganaRajanna Sircilla);
INSERT INTO districts(state,district) VALUES(TelanganaRangareddy);
INSERT INTO districts(state,district) VALUES(TelanganaSangareddy);
INSERT INTO districts(state,district) VALUES(TelanganaSiddipet);
INSERT INTO districts(state,district) VALUES(TelanganaSuryapet);
INSERT INTO districts(state,district) VALUES(TelanganaVikarabad);
INSERT INTO districts(state,district) VALUES(TelanganaWanaparthy);
INSERT INTO districts(state,district) VALUES(TelanganaWarangal (Rural));
INSERT INTO districts(state,district) VALUES(TelanganaWarangal (Urban));
INSERT INTO districts(state,district) VALUES(TelanganaYadadri Bhuvanagiri);
INSERT INTO districts(state,district) VALUES(TripuraDhalai);
INSERT INTO districts(state,district) VALUES(TripuraGomati);
INSERT INTO districts(state,district) VALUES(TripuraKhowai);
INSERT INTO districts(state,district) VALUES(TripuraNorth Tripura);
INSERT INTO districts(state,district) VALUES(TripuraSepahijala);
INSERT INTO districts(state,district) VALUES(TripuraSouth Tripura);
INSERT INTO districts(state,district) VALUES(TripuraUnakoti);
INSERT INTO districts(state,district) VALUES(TripuraWest Tripura);
INSERT INTO districts(state,district) VALUES(UttarakhandAlmora);
INSERT INTO districts(state,district) VALUES(UttarakhandBageshwar);
INSERT INTO districts(state,district) VALUES(UttarakhandChamoli);
INSERT INTO districts(state,district) VALUES(UttarakhandChampawat);
INSERT INTO districts(state,district) VALUES(UttarakhandDehradun);
INSERT INTO districts(state,district) VALUES(UttarakhandHaridwar);
INSERT INTO districts(state,district) VALUES(UttarakhandNainital);
INSERT INTO districts(state,district) VALUES(UttarakhandPauri Garhwal);
INSERT INTO districts(state,district) VALUES(UttarakhandPithoragarh);
INSERT INTO districts(state,district) VALUES(UttarakhandRudraprayag);
INSERT INTO districts(state,district) VALUES(UttarakhandTehri Garhwal);
INSERT INTO districts(state,district) VALUES(UttarakhandUdham Singh Nagar);
INSERT INTO districts(state,district) VALUES(UttarakhandUttarkashi);
INSERT INTO districts(state,district) VALUES(Uttar PradeshAgra);
INSERT INTO districts(state,district) VALUES(Uttar PradeshAligarh);
INSERT INTO districts(state,district) VALUES(Uttar PradeshAllahabad);
INSERT INTO districts(state,district) VALUES(Uttar PradeshAmbedkar Nagar);
INSERT INTO districts(state,district) VALUES(Uttar PradeshAmethi (Chatrapati Sahuji Mahraj Nagar));
INSERT INTO districts(state,district) VALUES(Uttar PradeshAmroha (J.P. Nagar));
INSERT INTO districts(state,district) VALUES(Uttar PradeshAuraiya);
INSERT INTO districts(state,district) VALUES(Uttar PradeshAzamgarh);
INSERT INTO districts(state,district) VALUES(Uttar PradeshBaghpat);
INSERT INTO districts(state,district) VALUES(Uttar PradeshBahraich);
INSERT INTO districts(state,district) VALUES(Uttar PradeshBallia);
INSERT INTO districts(state,district) VALUES(Uttar PradeshBalrampur);
INSERT INTO districts(state,district) VALUES(Uttar PradeshBanda);
INSERT INTO districts(state,district) VALUES(Uttar PradeshBarabanki);
INSERT INTO districts(state,district) VALUES(Uttar PradeshBareilly);
INSERT INTO districts(state,district) VALUES(Uttar PradeshBasti);
INSERT INTO districts(state,district) VALUES(Uttar PradeshBhadohi);
INSERT INTO districts(state,district) VALUES(Uttar PradeshBijnor);
INSERT INTO districts(state,district) VALUES(Uttar PradeshBudaun);
INSERT INTO districts(state,district) VALUES(Uttar PradeshBulandshahr);
INSERT INTO districts(state,district) VALUES(Uttar PradeshChandauli);
INSERT INTO districts(state,district) VALUES(Uttar PradeshChitrakoot);
INSERT INTO districts(state,district) VALUES(Uttar PradeshDeoria);
INSERT INTO districts(state,district) VALUES(Uttar PradeshEtah);
INSERT INTO districts(state,district) VALUES(Uttar PradeshEtawah);
INSERT INTO districts(state,district) VALUES(Uttar PradeshFaizabad);
INSERT INTO districts(state,district) VALUES(Uttar PradeshFarrukhabad);
INSERT INTO districts(state,district) VALUES(Uttar PradeshFatehpur);
INSERT INTO districts(state,district) VALUES(Uttar PradeshFirozabad);
INSERT INTO districts(state,district) VALUES(Uttar PradeshGautam Buddha Nagar);
INSERT INTO districts(state,district) VALUES(Uttar PradeshGhaziabad);
INSERT INTO districts(state,district) VALUES(Uttar PradeshGhazipur);
INSERT INTO districts(state,district) VALUES(Uttar PradeshGonda);
INSERT INTO districts(state,district) VALUES(Uttar PradeshGorakhpur);
INSERT INTO districts(state,district) VALUES(Uttar PradeshHamirpur);
INSERT INTO districts(state,district) VALUES(Uttar PradeshHapur (Panchsheel Nagar));
INSERT INTO districts(state,district) VALUES(Uttar PradeshHardoi);
INSERT INTO districts(state,district) VALUES(Uttar PradeshHathras);
INSERT INTO districts(state,district) VALUES(Uttar PradeshJalaun);
INSERT INTO districts(state,district) VALUES(Uttar PradeshJaunpur);
INSERT INTO districts(state,district) VALUES(Uttar PradeshJhansi);
INSERT INTO districts(state,district) VALUES(Uttar PradeshKannauj);
INSERT INTO districts(state,district) VALUES(Uttar PradeshKanpur Dehat);
INSERT INTO districts(state,district) VALUES(Uttar PradeshKanpur Nagar);
INSERT INTO districts(state,district) VALUES(Uttar PradeshKanshiram Nagar (Kasganj));
INSERT INTO districts(state,district) VALUES(Uttar PradeshKaushambi);
INSERT INTO districts(state,district) VALUES(Uttar PradeshKushinagar (Padrauna));
INSERT INTO districts(state,district) VALUES(Uttar PradeshLakhimpur - Kheri);
INSERT INTO districts(state,district) VALUES(Uttar PradeshLalitpur);
INSERT INTO districts(state,district) VALUES(Uttar PradeshLucknow);
INSERT INTO districts(state,district) VALUES(Uttar PradeshMaharajganj);
INSERT INTO districts(state,district) VALUES(Uttar PradeshMahoba);
INSERT INTO districts(state,district) VALUES(Uttar PradeshMainpuri);
INSERT INTO districts(state,district) VALUES(Uttar PradeshMathura);
INSERT INTO districts(state,district) VALUES(Uttar PradeshMau);
INSERT INTO districts(state,district) VALUES(Uttar PradeshMeerut);
INSERT INTO districts(state,district) VALUES(Uttar PradeshMirzapur);
INSERT INTO districts(state,district) VALUES(Uttar PradeshMoradabad);
INSERT INTO districts(state,district) VALUES(Uttar PradeshMuzaffarnagar);
INSERT INTO districts(state,district) VALUES(Uttar PradeshPilibhit);
INSERT INTO districts(state,district) VALUES(Uttar PradeshPratapgarh);
INSERT INTO districts(state,district) VALUES(Uttar PradeshRaeBareli);
INSERT INTO districts(state,district) VALUES(Uttar PradeshRampur);
INSERT INTO districts(state,district) VALUES(Uttar PradeshSaharanpur);
INSERT INTO districts(state,district) VALUES(Uttar PradeshSambhal (Bhim Nagar));
INSERT INTO districts(state,district) VALUES(Uttar PradeshSant Kabir Nagar);
INSERT INTO districts(state,district) VALUES(Uttar PradeshShahjahanpur);
INSERT INTO districts(state,district) VALUES(Uttar PradeshShamali (Prabuddh Nagar));
INSERT INTO districts(state,district) VALUES(Uttar PradeshShravasti);
INSERT INTO districts(state,district) VALUES(Uttar PradeshSiddharth Nagar);
INSERT INTO districts(state,district) VALUES(Uttar PradeshSitapur);
INSERT INTO districts(state,district) VALUES(Uttar PradeshSonbhadra);
INSERT INTO districts(state,district) VALUES(Uttar PradeshSultanpur);
INSERT INTO districts(state,district) VALUES(Uttar PradeshUnnao);
INSERT INTO districts(state,district) VALUES(Uttar PradeshVaranasi);
INSERT INTO districts(state,district) VALUES(West BengalAlipurduar);
INSERT INTO districts(state,district) VALUES(West BengalBankura);
INSERT INTO districts(state,district) VALUES(West BengalBirbhum);
INSERT INTO districts(state,district) VALUES(West BengalBurdwan (Bardhaman));
INSERT INTO districts(state,district) VALUES(West BengalCooch Behar);
INSERT INTO districts(state,district) VALUES(West BengalDakshin Dinajpur (South Dinajpur));
INSERT INTO districts(state,district) VALUES(West BengalDarjeeling);
INSERT INTO districts(state,district) VALUES(West BengalHooghly);
INSERT INTO districts(state,district) VALUES(West BengalHowrah);
INSERT INTO districts(state,district) VALUES(West BengalJalpaiguri);
INSERT INTO districts(state,district) VALUES(West BengalKalimpong);
INSERT INTO districts(state,district) VALUES(West BengalKolkata);
INSERT INTO districts(state,district) VALUES(West BengalMalda);
INSERT INTO districts(state,district) VALUES(West BengalMurshidabad);
INSERT INTO districts(state,district) VALUES(West BengalNadia);
INSERT INTO districts(state,district) VALUES(West BengalNorth 24 Parganas);
INSERT INTO districts(state,district) VALUES(West BengalPaschim Medinipur (West Medinipur));
INSERT INTO districts(state,district) VALUES(West BengalPurba Medinipur (East Medinipur));
INSERT INTO districts(state,district) VALUES(West BengalPurulia);
INSERT INTO districts(state,district) VALUES(West BengalSouth 24 Parganas);
INSERT INTO districts(state,district) VALUES(West BengalUttar Dinajpur (North Dinajpur));
