INSERT INTO districts(state,district) VALUES('Andhra Pradesh','Anantapur');
INSERT INTO districts(state,district) VALUES('Andhra Pradesh','Chittoor');
INSERT INTO districts(state,district) VALUES('Andhra Pradesh','East Godavari');
INSERT INTO districts(state,district) VALUES('Andhra Pradesh','Guntur');
INSERT INTO districts(state,district) VALUES('Andhra Pradesh','Krishna');
INSERT INTO districts(state,district) VALUES('Andhra Pradesh','Kurnool');
INSERT INTO districts(state,district) VALUES('Andhra Pradesh','Nellore');
INSERT INTO districts(state,district) VALUES('Andhra Pradesh','Prakasam');
INSERT INTO districts(state,district) VALUES('Andhra Pradesh','Srikakulam');
INSERT INTO districts(state,district) VALUES('Andhra Pradesh','Visakhapatnam');
INSERT INTO districts(state,district) VALUES('Andhra Pradesh','Vizianagaram');
INSERT INTO districts(state,district) VALUES('Andhra Pradesh','West Godavari');
INSERT INTO districts(state,district) VALUES('Andhra Pradesh','YSR Kadapa');
INSERT INTO districts(state,district) VALUES('Arunachal Pradesh','Tawang');
INSERT INTO districts(state,district) VALUES('Arunachal Pradesh','West Kameng');
INSERT INTO districts(state,district) VALUES('Arunachal Pradesh','East Kameng');
INSERT INTO districts(state,district) VALUES('Arunachal Pradesh','Papum Pare');
INSERT INTO districts(state,district) VALUES('Arunachal Pradesh','Kurung Kumey');
INSERT INTO districts(state,district) VALUES('Arunachal Pradesh','Kra Daadi');
INSERT INTO districts(state,district) VALUES('Arunachal Pradesh','Lower Subansiri');
INSERT INTO districts(state,district) VALUES('Arunachal Pradesh','Upper Subansiri');
INSERT INTO districts(state,district) VALUES('Arunachal Pradesh','West Siang');
INSERT INTO districts(state,district) VALUES('Arunachal Pradesh','East Siang');
INSERT INTO districts(state,district) VALUES('Arunachal Pradesh','Siang');
INSERT INTO districts(state,district) VALUES('Arunachal Pradesh','Upper Siang');
INSERT INTO districts(state,district) VALUES('Arunachal Pradesh','Lower Siang');
INSERT INTO districts(state,district) VALUES('Arunachal Pradesh','Lower Dibang Valley');
INSERT INTO districts(state,district) VALUES('Arunachal Pradesh','Dibang Valley');
INSERT INTO districts(state,district) VALUES('Arunachal Pradesh','Anjaw');
INSERT INTO districts(state,district) VALUES('Arunachal Pradesh','Lohit');
INSERT INTO districts(state,district) VALUES('Arunachal Pradesh','Namsai');
INSERT INTO districts(state,district) VALUES('Arunachal Pradesh','Changlang');
INSERT INTO districts(state,district) VALUES('Arunachal Pradesh','Tirap');
INSERT INTO districts(state,district) VALUES('Arunachal Pradesh','Longding');
INSERT INTO districts(state,district) VALUES('Assam','Baksa');
INSERT INTO districts(state,district) VALUES('Assam','Barpeta');
INSERT INTO districts(state,district) VALUES('Assam','Biswanath');
INSERT INTO districts(state,district) VALUES('Assam','Bongaigaon');
INSERT INTO districts(state,district) VALUES('Assam','Cachar');
INSERT INTO districts(state,district) VALUES('Assam','Charaideo');
INSERT INTO districts(state,district) VALUES('Assam','Chirang');
INSERT INTO districts(state,district) VALUES('Assam','Darrang');
INSERT INTO districts(state,district) VALUES('Assam','Dhemaji');
INSERT INTO districts(state,district) VALUES('Assam','Dhubri');
INSERT INTO districts(state,district) VALUES('Assam','Dibrugarh');
INSERT INTO districts(state,district) VALUES('Assam','Goalpara');
INSERT INTO districts(state,district) VALUES('Assam','Golaghat');
INSERT INTO districts(state,district) VALUES('Assam','Hailakandi');
INSERT INTO districts(state,district) VALUES('Assam','Hojai');
INSERT INTO districts(state,district) VALUES('Assam','Jorhat');
INSERT INTO districts(state,district) VALUES('Assam','Kamrup Metropolitan');
INSERT INTO districts(state,district) VALUES('Assam','Kamrup');
INSERT INTO districts(state,district) VALUES('Assam','Karbi Anglong');
INSERT INTO districts(state,district) VALUES('Assam','Karimganj');
INSERT INTO districts(state,district) VALUES('Assam','Kokrajhar');
INSERT INTO districts(state,district) VALUES('Assam','Lakhimpur');
INSERT INTO districts(state,district) VALUES('Assam','Majuli');
INSERT INTO districts(state,district) VALUES('Assam','Morigaon');
INSERT INTO districts(state,district) VALUES('Assam','Nagaon');
INSERT INTO districts(state,district) VALUES('Assam','Nalbari');
INSERT INTO districts(state,district) VALUES('Assam','Dima Hasao');
INSERT INTO districts(state,district) VALUES('Assam','Sivasagar');
INSERT INTO districts(state,district) VALUES('Assam','Sonitpur');
INSERT INTO districts(state,district) VALUES('Assam','South Salmara-Mankachar');
INSERT INTO districts(state,district) VALUES('Assam','Tinsukia');
INSERT INTO districts(state,district) VALUES('Assam','Udalguri');
INSERT INTO districts(state,district) VALUES('Assam','West Karbi Anglong');
INSERT INTO districts(state,district) VALUES('Bihar','Araria');
INSERT INTO districts(state,district) VALUES('Bihar','Arwal');
INSERT INTO districts(state,district) VALUES('Bihar','Aurangabad');
INSERT INTO districts(state,district) VALUES('Bihar','Banka');
INSERT INTO districts(state,district) VALUES('Bihar','Begusarai');
INSERT INTO districts(state,district) VALUES('Bihar','Bhagalpur');
INSERT INTO districts(state,district) VALUES('Bihar','Bhojpur');
INSERT INTO districts(state,district) VALUES('Bihar','Buxar');
INSERT INTO districts(state,district) VALUES('Bihar','Darbhanga');
INSERT INTO districts(state,district) VALUES('Bihar','East Champaran (Motihari)');
INSERT INTO districts(state,district) VALUES('Bihar','Gaya');
INSERT INTO districts(state,district) VALUES('Bihar','Gopalganj');
INSERT INTO districts(state,district) VALUES('Bihar','Jamui');
INSERT INTO districts(state,district) VALUES('Bihar','Jehanabad');
INSERT INTO districts(state,district) VALUES('Bihar','Kaimur (Bhabua)');
INSERT INTO districts(state,district) VALUES('Bihar','Katihar');
INSERT INTO districts(state,district) VALUES('Bihar','Khagaria');
INSERT INTO districts(state,district) VALUES('Bihar','Kishanganj');
INSERT INTO districts(state,district) VALUES('Bihar','Lakhisarai');
INSERT INTO districts(state,district) VALUES('Bihar','Madhepura');
INSERT INTO districts(state,district) VALUES('Bihar','Madhubani');
INSERT INTO districts(state,district) VALUES('Bihar','Munger (Monghyr)');
INSERT INTO districts(state,district) VALUES('Bihar','Muzaffarpur');
INSERT INTO districts(state,district) VALUES('Bihar','Nalanda');
INSERT INTO districts(state,district) VALUES('Bihar','Nawada');
INSERT INTO districts(state,district) VALUES('Bihar','Patna');
INSERT INTO districts(state,district) VALUES('Bihar','Purnia (Purnea)');
INSERT INTO districts(state,district) VALUES('Bihar','Rohtas');
INSERT INTO districts(state,district) VALUES('Bihar','Saharsa');
INSERT INTO districts(state,district) VALUES('Bihar','Samastipur');
INSERT INTO districts(state,district) VALUES('Bihar','Saran');
INSERT INTO districts(state,district) VALUES('Bihar','Sheikhpura');
INSERT INTO districts(state,district) VALUES('Bihar','Sheohar');
INSERT INTO districts(state,district) VALUES('Bihar','Sitamarhi');
INSERT INTO districts(state,district) VALUES('Bihar','Siwan');
INSERT INTO districts(state,district) VALUES('Bihar','Supaul');
INSERT INTO districts(state,district) VALUES('Bihar','Vaishali');
INSERT INTO districts(state,district) VALUES('Bihar','West Champaran');
INSERT INTO districts(state,district) VALUES('Chandigarh (UT)','Chandigarh');
INSERT INTO districts(state,district) VALUES('Chhattisgarh','Balod');
INSERT INTO districts(state,district) VALUES('Chhattisgarh','Baloda Bazar');
INSERT INTO districts(state,district) VALUES('Chhattisgarh','Balrampur');
INSERT INTO districts(state,district) VALUES('Chhattisgarh','Bastar');
INSERT INTO districts(state,district) VALUES('Chhattisgarh','Bemetara');
INSERT INTO districts(state,district) VALUES('Chhattisgarh','Bijapur');
INSERT INTO districts(state,district) VALUES('Chhattisgarh','Bilaspur');
INSERT INTO districts(state,district) VALUES('Chhattisgarh','Dantewada (South Bastar)');
INSERT INTO districts(state,district) VALUES('Chhattisgarh','Dhamtari');
INSERT INTO districts(state,district) VALUES('Chhattisgarh','Durg');
INSERT INTO districts(state,district) VALUES('Chhattisgarh','Gariyaband');
INSERT INTO districts(state,district) VALUES('Chhattisgarh','Janjgir-Champa');
INSERT INTO districts(state,district) VALUES('Chhattisgarh','Jashpur');
INSERT INTO districts(state,district) VALUES('Chhattisgarh','Kabirdham (Kawardha)');
INSERT INTO districts(state,district) VALUES('Chhattisgarh','Kanker (North Bastar)');
INSERT INTO districts(state,district) VALUES('Chhattisgarh','Kondagaon');
INSERT INTO districts(state,district) VALUES('Chhattisgarh','Korba');
INSERT INTO districts(state,district) VALUES('Chhattisgarh','Korea (Koriya)');
INSERT INTO districts(state,district) VALUES('Chhattisgarh','Mahasamund');
INSERT INTO districts(state,district) VALUES('Chhattisgarh','Mungeli');
INSERT INTO districts(state,district) VALUES('Chhattisgarh','Narayanpur');
INSERT INTO districts(state,district) VALUES('Chhattisgarh','Raigarh');
INSERT INTO districts(state,district) VALUES('Chhattisgarh','Raipur');
INSERT INTO districts(state,district) VALUES('Chhattisgarh','Rajnandgaon');
INSERT INTO districts(state,district) VALUES('Chhattisgarh','Sukma');
INSERT INTO districts(state,district) VALUES('Chhattisgarh','Surajpur  ');
INSERT INTO districts(state,district) VALUES('Chhattisgarh','Surguja');
INSERT INTO districts(state,district) VALUES('Dadra and Nagar Haveli (UT)','Dadra & Nagar Haveli');
INSERT INTO districts(state,district) VALUES('Daman and Diu (UT)','Daman');
INSERT INTO districts(state,district) VALUES('Daman and Diu (UT)','Diu');
INSERT INTO districts(state,district) VALUES('Delhi (NCT)','Central Delhi');
INSERT INTO districts(state,district) VALUES('Delhi (NCT)','East Delhi');
INSERT INTO districts(state,district) VALUES('Delhi (NCT)','New Delhi');
INSERT INTO districts(state,district) VALUES('Delhi (NCT)','North Delhi');
INSERT INTO districts(state,district) VALUES('Delhi (NCT)','North East  Delhi');
INSERT INTO districts(state,district) VALUES('Delhi (NCT)','North West  Delhi');
INSERT INTO districts(state,district) VALUES('Delhi (NCT)','Shahdara');
INSERT INTO districts(state,district) VALUES('Delhi (NCT)','South Delhi');
INSERT INTO districts(state,district) VALUES('Delhi (NCT)','South East Delhi');
INSERT INTO districts(state,district) VALUES('Delhi (NCT)','South West  Delhi');
INSERT INTO districts(state,district) VALUES('Delhi (NCT)','West Delhi');
INSERT INTO districts(state,district) VALUES('Goa','North Goa');
INSERT INTO districts(state,district) VALUES('Goa','South Goa');
INSERT INTO districts(state,district) VALUES('Gujarat','Ahmedabad');
INSERT INTO districts(state,district) VALUES('Gujarat','Amreli');
INSERT INTO districts(state,district) VALUES('Gujarat','Anand');
INSERT INTO districts(state,district) VALUES('Gujarat','Aravalli');
INSERT INTO districts(state,district) VALUES('Gujarat','Banaskantha (Palanpur)');
INSERT INTO districts(state,district) VALUES('Gujarat','Bharuch');
INSERT INTO districts(state,district) VALUES('Gujarat','Bhavnagar');
INSERT INTO districts(state,district) VALUES('Gujarat','Botad');
INSERT INTO districts(state,district) VALUES('Gujarat','Chhota Udepur');
INSERT INTO districts(state,district) VALUES('Gujarat','Dahod');
INSERT INTO districts(state,district) VALUES('Gujarat','Dangs (Ahwa)');
INSERT INTO districts(state,district) VALUES('Gujarat','Devbhoomi Dwarka');
INSERT INTO districts(state,district) VALUES('Gujarat','Gandhinagar');
INSERT INTO districts(state,district) VALUES('Gujarat','Gir Somnath');
INSERT INTO districts(state,district) VALUES('Gujarat','Jamnagar');
INSERT INTO districts(state,district) VALUES('Gujarat','Junagadh');
INSERT INTO districts(state,district) VALUES('Gujarat','Kachchh');
INSERT INTO districts(state,district) VALUES('Gujarat','Kheda (Nadiad)');
INSERT INTO districts(state,district) VALUES('Gujarat','Mahisagar');
INSERT INTO districts(state,district) VALUES('Gujarat','Mehsana');
INSERT INTO districts(state,district) VALUES('Gujarat','Morbi');
INSERT INTO districts(state,district) VALUES('Gujarat','Narmada (Rajpipla)');
INSERT INTO districts(state,district) VALUES('Gujarat','Navsari');
INSERT INTO districts(state,district) VALUES('Gujarat','Panchmahal (Godhra)');
INSERT INTO districts(state,district) VALUES('Gujarat','Patan');
INSERT INTO districts(state,district) VALUES('Gujarat','Porbandar');
INSERT INTO districts(state,district) VALUES('Gujarat','Rajkot');
INSERT INTO districts(state,district) VALUES('Gujarat','Sabarkantha (Himmatnagar)');
INSERT INTO districts(state,district) VALUES('Gujarat','Surat');
INSERT INTO districts(state,district) VALUES('Gujarat','Surendranagar');
INSERT INTO districts(state,district) VALUES('Gujarat','Tapi (Vyara)');
INSERT INTO districts(state,district) VALUES('Gujarat','Vadodara');
INSERT INTO districts(state,district) VALUES('Gujarat','Valsad');
INSERT INTO districts(state,district) VALUES('Haryana','Ambala');
INSERT INTO districts(state,district) VALUES('Haryana','Bhiwani');
INSERT INTO districts(state,district) VALUES('Haryana','Charkhi Dadri');
INSERT INTO districts(state,district) VALUES('Haryana','Faridabad');
INSERT INTO districts(state,district) VALUES('Haryana','Fatehabad');
INSERT INTO districts(state,district) VALUES('Haryana','Gurgaon');
INSERT INTO districts(state,district) VALUES('Haryana','Hisar');
INSERT INTO districts(state,district) VALUES('Haryana','Jhajjar');
INSERT INTO districts(state,district) VALUES('Haryana','Jind');
INSERT INTO districts(state,district) VALUES('Haryana','Kaithal');
INSERT INTO districts(state,district) VALUES('Haryana','Karnal');
INSERT INTO districts(state,district) VALUES('Haryana','Kurukshetra');
INSERT INTO districts(state,district) VALUES('Haryana','Mahendragarh');
INSERT INTO districts(state,district) VALUES('Haryana','Mewat');
INSERT INTO districts(state,district) VALUES('Haryana','Palwal');
INSERT INTO districts(state,district) VALUES('Haryana','Panchkula');
INSERT INTO districts(state,district) VALUES('Haryana','Panipat');
INSERT INTO districts(state,district) VALUES('Haryana','Rewari');
INSERT INTO districts(state,district) VALUES('Haryana','Rohtak');
INSERT INTO districts(state,district) VALUES('Haryana','Sirsa');
INSERT INTO districts(state,district) VALUES('Haryana','Sonipat');
INSERT INTO districts(state,district) VALUES('Haryana','Yamunanagar');
INSERT INTO districts(state,district) VALUES('Himachal Pradesh','Bilaspur');
INSERT INTO districts(state,district) VALUES('Himachal Pradesh','Chamba');
INSERT INTO districts(state,district) VALUES('Himachal Pradesh','Hamirpur');
INSERT INTO districts(state,district) VALUES('Himachal Pradesh','Kangra');
INSERT INTO districts(state,district) VALUES('Himachal Pradesh','Kinnaur');
INSERT INTO districts(state,district) VALUES('Himachal Pradesh','Kullu');
INSERT INTO districts(state,district) VALUES('Himachal Pradesh','Lahaul &amp; Spiti');
INSERT INTO districts(state,district) VALUES('Himachal Pradesh','Mandi');
INSERT INTO districts(state,district) VALUES('Himachal Pradesh','Shimla');
INSERT INTO districts(state,district) VALUES('Himachal Pradesh','Sirmaur (Sirmour)');
INSERT INTO districts(state,district) VALUES('Himachal Pradesh','Solan');
INSERT INTO districts(state,district) VALUES('Himachal Pradesh','Una');
INSERT INTO districts(state,district) VALUES('Jammu and Kashmir','Anantnag');
INSERT INTO districts(state,district) VALUES('Jammu and Kashmir','Bandipore');
INSERT INTO districts(state,district) VALUES('Jammu and Kashmir','Baramulla');
INSERT INTO districts(state,district) VALUES('Jammu and Kashmir','Budgam');
INSERT INTO districts(state,district) VALUES('Jammu and Kashmir','Doda');
INSERT INTO districts(state,district) VALUES('Jammu and Kashmir','Ganderbal');
INSERT INTO districts(state,district) VALUES('Jammu and Kashmir','Jammu');
INSERT INTO districts(state,district) VALUES('Jammu and Kashmir','Kargil');
INSERT INTO districts(state,district) VALUES('Jammu and Kashmir','Kathua');
INSERT INTO districts(state,district) VALUES('Jammu and Kashmir','Kishtwar');
INSERT INTO districts(state,district) VALUES('Jammu and Kashmir','Kulgam');
INSERT INTO districts(state,district) VALUES('Jammu and Kashmir','Kupwara');
INSERT INTO districts(state,district) VALUES('Jammu and Kashmir','Leh');
INSERT INTO districts(state,district) VALUES('Jammu and Kashmir','Poonch');
INSERT INTO districts(state,district) VALUES('Jammu and Kashmir','Pulwama');
INSERT INTO districts(state,district) VALUES('Jammu and Kashmir','Rajouri');
INSERT INTO districts(state,district) VALUES('Jammu and Kashmir','Ramban');
INSERT INTO districts(state,district) VALUES('Jammu and Kashmir','Reasi');
INSERT INTO districts(state,district) VALUES('Jammu and Kashmir','Samba');
INSERT INTO districts(state,district) VALUES('Jammu and Kashmir','Shopian');
INSERT INTO districts(state,district) VALUES('Jammu and Kashmir','Srinagar');
INSERT INTO districts(state,district) VALUES('Jammu and Kashmir','Udhampur');
INSERT INTO districts(state,district) VALUES('Jharkhand','Bokaro');
INSERT INTO districts(state,district) VALUES('Jharkhand','Chatra');
INSERT INTO districts(state,district) VALUES('Jharkhand','Deoghar');
INSERT INTO districts(state,district) VALUES('Jharkhand','Dhanbad');
INSERT INTO districts(state,district) VALUES('Jharkhand','Dumka');
INSERT INTO districts(state,district) VALUES('Jharkhand','East Singhbhum');
INSERT INTO districts(state,district) VALUES('Jharkhand','Garhwa');
INSERT INTO districts(state,district) VALUES('Jharkhand','Giridih');
INSERT INTO districts(state,district) VALUES('Jharkhand','Godda');
INSERT INTO districts(state,district) VALUES('Jharkhand','Gumla');
INSERT INTO districts(state,district) VALUES('Jharkhand','Hazaribag');
INSERT INTO districts(state,district) VALUES('Jharkhand','Jamtara');
INSERT INTO districts(state,district) VALUES('Jharkhand','Khunti');
INSERT INTO districts(state,district) VALUES('Jharkhand','Koderma');
INSERT INTO districts(state,district) VALUES('Jharkhand','Latehar');
INSERT INTO districts(state,district) VALUES('Jharkhand','Lohardaga');
INSERT INTO districts(state,district) VALUES('Jharkhand','Pakur');
INSERT INTO districts(state,district) VALUES('Jharkhand','Palamu');
INSERT INTO districts(state,district) VALUES('Jharkhand','Ramgarh');
INSERT INTO districts(state,district) VALUES('Jharkhand','Ranchi');
INSERT INTO districts(state,district) VALUES('Jharkhand','Sahibganj');
INSERT INTO districts(state,district) VALUES('Jharkhand','Seraikela-Kharsawan');
INSERT INTO districts(state,district) VALUES('Jharkhand','Simdega');
INSERT INTO districts(state,district) VALUES('Jharkhand','West Singhbhum');
INSERT INTO districts(state,district) VALUES('Karnataka','Bagalkot');
INSERT INTO districts(state,district) VALUES('Karnataka','Ballari (Bellary)');
INSERT INTO districts(state,district) VALUES('Karnataka','Belagavi (Belgaum)');
INSERT INTO districts(state,district) VALUES('Karnataka','Bengaluru (Bangalore) Rural');
INSERT INTO districts(state,district) VALUES('Karnataka','Bengaluru (Bangalore) Urban');
INSERT INTO districts(state,district) VALUES('Karnataka','Bidar');
INSERT INTO districts(state,district) VALUES('Karnataka','Chamarajanagar');
INSERT INTO districts(state,district) VALUES('Karnataka','Chikballapur');
INSERT INTO districts(state,district) VALUES('Karnataka','Chikkamagaluru (Chikmagalur)');
INSERT INTO districts(state,district) VALUES('Karnataka','Chitradurga');
INSERT INTO districts(state,district) VALUES('Karnataka','Dakshina Kannada');
INSERT INTO districts(state,district) VALUES('Karnataka','Davangere');
INSERT INTO districts(state,district) VALUES('Karnataka','Dharwad');
INSERT INTO districts(state,district) VALUES('Karnataka','Gadag');
INSERT INTO districts(state,district) VALUES('Karnataka','Hassan');
INSERT INTO districts(state,district) VALUES('Karnataka','Haveri');
INSERT INTO districts(state,district) VALUES('Karnataka','Kalaburagi (Gulbarga)');
INSERT INTO districts(state,district) VALUES('Karnataka','Kodagu');
INSERT INTO districts(state,district) VALUES('Karnataka','Kolar');
INSERT INTO districts(state,district) VALUES('Karnataka','Koppal');
INSERT INTO districts(state,district) VALUES('Karnataka','Mandya');
INSERT INTO districts(state,district) VALUES('Karnataka','Mysuru (Mysore)');
INSERT INTO districts(state,district) VALUES('Karnataka','Raichur');
INSERT INTO districts(state,district) VALUES('Karnataka','Ramanagara');
INSERT INTO districts(state,district) VALUES('Karnataka','Shivamogga (Shimoga)');
INSERT INTO districts(state,district) VALUES('Karnataka','Tumakuru (Tumkur)');
INSERT INTO districts(state,district) VALUES('Karnataka','Udupi');
INSERT INTO districts(state,district) VALUES('Karnataka','Uttara Kannada (Karwar)');
INSERT INTO districts(state,district) VALUES('Karnataka','Vijayapura (Bijapur)');
INSERT INTO districts(state,district) VALUES('Karnataka','Yadgir');
INSERT INTO districts(state,district) VALUES('Kerala','Alappuzha');
INSERT INTO districts(state,district) VALUES('Kerala','Ernakulam');
INSERT INTO districts(state,district) VALUES('Kerala','Idukki');
INSERT INTO districts(state,district) VALUES('Kerala','Kannur');
INSERT INTO districts(state,district) VALUES('Kerala','Kasaragod');
INSERT INTO districts(state,district) VALUES('Kerala','Kollam');
INSERT INTO districts(state,district) VALUES('Kerala','Kottayam');
INSERT INTO districts(state,district) VALUES('Kerala','Kozhikode');
INSERT INTO districts(state,district) VALUES('Kerala','Malappuram');
INSERT INTO districts(state,district) VALUES('Kerala','Palakkad');
INSERT INTO districts(state,district) VALUES('Kerala','Pathanamthitta');
INSERT INTO districts(state,district) VALUES('Kerala','Thiruvananthapuram');
INSERT INTO districts(state,district) VALUES('Kerala','Thrissur');
INSERT INTO districts(state,district) VALUES('Kerala','Wayanad');
INSERT INTO districts(state,district) VALUES('Lakshadweep (UT)','Agatti');
INSERT INTO districts(state,district) VALUES('Lakshadweep (UT)','Amini');
INSERT INTO districts(state,district) VALUES('Lakshadweep (UT)','Androth');
INSERT INTO districts(state,district) VALUES('Lakshadweep (UT)','Bithra');
INSERT INTO districts(state,district) VALUES('Lakshadweep (UT)','Chethlath');
INSERT INTO districts(state,district) VALUES('Lakshadweep (UT)','Kavaratti');
INSERT INTO districts(state,district) VALUES('Lakshadweep (UT)','Kadmath');
INSERT INTO districts(state,district) VALUES('Lakshadweep (UT)','Kalpeni');
INSERT INTO districts(state,district) VALUES('Lakshadweep (UT)','Kilthan');
INSERT INTO districts(state,district) VALUES('Lakshadweep (UT)','Minicoy');
INSERT INTO districts(state,district) VALUES('Madhya Pradesh','Agar Malwa');
INSERT INTO districts(state,district) VALUES('Madhya Pradesh','Alirajpur');
INSERT INTO districts(state,district) VALUES('Madhya Pradesh','Anuppur');
INSERT INTO districts(state,district) VALUES('Madhya Pradesh','Ashoknagar');
INSERT INTO districts(state,district) VALUES('Madhya Pradesh','Balaghat');
INSERT INTO districts(state,district) VALUES('Madhya Pradesh','Barwani');
INSERT INTO districts(state,district) VALUES('Madhya Pradesh','Betul');
INSERT INTO districts(state,district) VALUES('Madhya Pradesh','Bhind');
INSERT INTO districts(state,district) VALUES('Madhya Pradesh','Bhopal');
INSERT INTO districts(state,district) VALUES('Madhya Pradesh','Burhanpur');
INSERT INTO districts(state,district) VALUES('Madhya Pradesh','Chhatarpur');
INSERT INTO districts(state,district) VALUES('Madhya Pradesh','Chhindwara');
INSERT INTO districts(state,district) VALUES('Madhya Pradesh','Damoh');
INSERT INTO districts(state,district) VALUES('Madhya Pradesh','Datia');
INSERT INTO districts(state,district) VALUES('Madhya Pradesh','Dewas');
INSERT INTO districts(state,district) VALUES('Madhya Pradesh','Dhar');
INSERT INTO districts(state,district) VALUES('Madhya Pradesh','Dindori');
INSERT INTO districts(state,district) VALUES('Madhya Pradesh','Guna');
INSERT INTO districts(state,district) VALUES('Madhya Pradesh','Gwalior');
INSERT INTO districts(state,district) VALUES('Madhya Pradesh','Harda');
INSERT INTO districts(state,district) VALUES('Madhya Pradesh','Hoshangabad');
INSERT INTO districts(state,district) VALUES('Madhya Pradesh','Indore');
INSERT INTO districts(state,district) VALUES('Madhya Pradesh','Jabalpur');
INSERT INTO districts(state,district) VALUES('Madhya Pradesh','Jhabua');
INSERT INTO districts(state,district) VALUES('Madhya Pradesh','Katni');
INSERT INTO districts(state,district) VALUES('Madhya Pradesh','Khandwa');
INSERT INTO districts(state,district) VALUES('Madhya Pradesh','Khargone');
INSERT INTO districts(state,district) VALUES('Madhya Pradesh','Mandla');
INSERT INTO districts(state,district) VALUES('Madhya Pradesh','Mandsaur');
INSERT INTO districts(state,district) VALUES('Madhya Pradesh','Morena');
INSERT INTO districts(state,district) VALUES('Madhya Pradesh','Narsinghpur');
INSERT INTO districts(state,district) VALUES('Madhya Pradesh','Neemuch');
INSERT INTO districts(state,district) VALUES('Madhya Pradesh','Panna');
INSERT INTO districts(state,district) VALUES('Madhya Pradesh','Raisen');
INSERT INTO districts(state,district) VALUES('Madhya Pradesh','Rajgarh');
INSERT INTO districts(state,district) VALUES('Madhya Pradesh','Ratlam');
INSERT INTO districts(state,district) VALUES('Madhya Pradesh','Rewa');
INSERT INTO districts(state,district) VALUES('Madhya Pradesh','Sagar');
INSERT INTO districts(state,district) VALUES('Madhya Pradesh','Satna');
INSERT INTO districts(state,district) VALUES('Madhya Pradesh','Sehore');
INSERT INTO districts(state,district) VALUES('Madhya Pradesh','Seoni');
INSERT INTO districts(state,district) VALUES('Madhya Pradesh','Shahdol');
INSERT INTO districts(state,district) VALUES('Madhya Pradesh','Shajapur');
INSERT INTO districts(state,district) VALUES('Madhya Pradesh','Sheopur');
INSERT INTO districts(state,district) VALUES('Madhya Pradesh','Shivpuri');
INSERT INTO districts(state,district) VALUES('Madhya Pradesh','Sidhi');
INSERT INTO districts(state,district) VALUES('Madhya Pradesh','Singrauli');
INSERT INTO districts(state,district) VALUES('Madhya Pradesh','Tikamgarh');
INSERT INTO districts(state,district) VALUES('Madhya Pradesh','Ujjain');
INSERT INTO districts(state,district) VALUES('Madhya Pradesh','Umaria');
INSERT INTO districts(state,district) VALUES('Madhya Pradesh','Vidisha');
INSERT INTO districts(state,district) VALUES('Maharashtra','Ahmednagar');
INSERT INTO districts(state,district) VALUES('Maharashtra','Akola');
INSERT INTO districts(state,district) VALUES('Maharashtra','Amravati');
INSERT INTO districts(state,district) VALUES('Maharashtra','Aurangabad');
INSERT INTO districts(state,district) VALUES('Maharashtra','Beed');
INSERT INTO districts(state,district) VALUES('Maharashtra','Bhandara');
INSERT INTO districts(state,district) VALUES('Maharashtra','Buldhana');
INSERT INTO districts(state,district) VALUES('Maharashtra','Chandrapur');
INSERT INTO districts(state,district) VALUES('Maharashtra','Dhule');
INSERT INTO districts(state,district) VALUES('Maharashtra','Gadchiroli');
INSERT INTO districts(state,district) VALUES('Maharashtra','Gondia');
INSERT INTO districts(state,district) VALUES('Maharashtra','Hingoli');
INSERT INTO districts(state,district) VALUES('Maharashtra','Jalgaon');
INSERT INTO districts(state,district) VALUES('Maharashtra','Jalna');
INSERT INTO districts(state,district) VALUES('Maharashtra','Kolhapur');
INSERT INTO districts(state,district) VALUES('Maharashtra','Latur');
INSERT INTO districts(state,district) VALUES('Maharashtra','Mumbai City');
INSERT INTO districts(state,district) VALUES('Maharashtra','Mumbai Suburban');
INSERT INTO districts(state,district) VALUES('Maharashtra','Nagpur');
INSERT INTO districts(state,district) VALUES('Maharashtra','Nanded');
INSERT INTO districts(state,district) VALUES('Maharashtra','Nandurbar');
INSERT INTO districts(state,district) VALUES('Maharashtra','Nashik');
INSERT INTO districts(state,district) VALUES('Maharashtra','Osmanabad');
INSERT INTO districts(state,district) VALUES('Maharashtra','Palghar');
INSERT INTO districts(state,district) VALUES('Maharashtra','Parbhani');
INSERT INTO districts(state,district) VALUES('Maharashtra','Pune');
INSERT INTO districts(state,district) VALUES('Maharashtra','Raigad');
INSERT INTO districts(state,district) VALUES('Maharashtra','Ratnagiri');
INSERT INTO districts(state,district) VALUES('Maharashtra','Sangli');
INSERT INTO districts(state,district) VALUES('Maharashtra','Satara');
INSERT INTO districts(state,district) VALUES('Maharashtra','Sindhudurg');
INSERT INTO districts(state,district) VALUES('Maharashtra','Solapur');
INSERT INTO districts(state,district) VALUES('Maharashtra','Thane');
INSERT INTO districts(state,district) VALUES('Maharashtra','Wardha');
INSERT INTO districts(state,district) VALUES('Maharashtra','Washim');
INSERT INTO districts(state,district) VALUES('Maharashtra','Yavatmal');
INSERT INTO districts(state,district) VALUES('Manipur','Bishnupur');
INSERT INTO districts(state,district) VALUES('Manipur','Chandel');
INSERT INTO districts(state,district) VALUES('Manipur','Churachandpur');
INSERT INTO districts(state,district) VALUES('Manipur','Imphal East');
INSERT INTO districts(state,district) VALUES('Manipur','Imphal West');
INSERT INTO districts(state,district) VALUES('Manipur','Jiribam');
INSERT INTO districts(state,district) VALUES('Manipur','Kakching');
INSERT INTO districts(state,district) VALUES('Manipur','Kamjong');
INSERT INTO districts(state,district) VALUES('Manipur','Kangpokpi');
INSERT INTO districts(state,district) VALUES('Manipur','Noney');
INSERT INTO districts(state,district) VALUES('Manipur','Pherzawl');
INSERT INTO districts(state,district) VALUES('Manipur','Senapati');
INSERT INTO districts(state,district) VALUES('Manipur','Tamenglong');
INSERT INTO districts(state,district) VALUES('Manipur','Tengnoupal');
INSERT INTO districts(state,district) VALUES('Manipur','Thoubal');
INSERT INTO districts(state,district) VALUES('Manipur','Ukhrul');
INSERT INTO districts(state,district) VALUES('Meghalaya','East Garo Hills');
INSERT INTO districts(state,district) VALUES('Meghalaya','East Jaintia Hills');
INSERT INTO districts(state,district) VALUES('Meghalaya','East Khasi Hills');
INSERT INTO districts(state,district) VALUES('Meghalaya','North Garo Hills');
INSERT INTO districts(state,district) VALUES('Meghalaya','Ri Bhoi');
INSERT INTO districts(state,district) VALUES('Meghalaya','South Garo Hills');
INSERT INTO districts(state,district) VALUES('Meghalaya','South West Garo Hills ');
INSERT INTO districts(state,district) VALUES('Meghalaya','South West Khasi Hills');
INSERT INTO districts(state,district) VALUES('Meghalaya','West Garo Hills');
INSERT INTO districts(state,district) VALUES('Meghalaya','West Jaintia Hills');
INSERT INTO districts(state,district) VALUES('Meghalaya','West Khasi Hills');
INSERT INTO districts(state,district) VALUES('Mizoram','Aizawl');
INSERT INTO districts(state,district) VALUES('Mizoram','Champhai');
INSERT INTO districts(state,district) VALUES('Mizoram','Kolasib');
INSERT INTO districts(state,district) VALUES('Mizoram','Lawngtlai');
INSERT INTO districts(state,district) VALUES('Mizoram','Lunglei');
INSERT INTO districts(state,district) VALUES('Mizoram','Mamit');
INSERT INTO districts(state,district) VALUES('Mizoram','Saiha');
INSERT INTO districts(state,district) VALUES('Mizoram','Serchhip');
INSERT INTO districts(state,district) VALUES('Nagaland','Dimapur');
INSERT INTO districts(state,district) VALUES('Nagaland','Kiphire');
INSERT INTO districts(state,district) VALUES('Nagaland','Kohima');
INSERT INTO districts(state,district) VALUES('Nagaland','Longleng');
INSERT INTO districts(state,district) VALUES('Nagaland','Mokokchung');
INSERT INTO districts(state,district) VALUES('Nagaland','Mon');
INSERT INTO districts(state,district) VALUES('Nagaland','Peren');
INSERT INTO districts(state,district) VALUES('Nagaland','Phek');
INSERT INTO districts(state,district) VALUES('Nagaland','Tuensang');
INSERT INTO districts(state,district) VALUES('Nagaland','Wokha');
INSERT INTO districts(state,district) VALUES('Nagaland','Zunheboto');
INSERT INTO districts(state,district) VALUES('Odisha','Angul');
INSERT INTO districts(state,district) VALUES('Odisha','Balangir');
INSERT INTO districts(state,district) VALUES('Odisha','Balasore');
INSERT INTO districts(state,district) VALUES('Odisha','Bargarh');
INSERT INTO districts(state,district) VALUES('Odisha','Bhadrak');
INSERT INTO districts(state,district) VALUES('Odisha','Boudh');
INSERT INTO districts(state,district) VALUES('Odisha','Cuttack');
INSERT INTO districts(state,district) VALUES('Odisha','Deogarh');
INSERT INTO districts(state,district) VALUES('Odisha','Dhenkanal');
INSERT INTO districts(state,district) VALUES('Odisha','Gajapati');
INSERT INTO districts(state,district) VALUES('Odisha','Ganjam');
INSERT INTO districts(state,district) VALUES('Odisha','Jagatsinghapur');
INSERT INTO districts(state,district) VALUES('Odisha','Jajpur');
INSERT INTO districts(state,district) VALUES('Odisha','Jharsuguda');
INSERT INTO districts(state,district) VALUES('Odisha','Kalahandi');
INSERT INTO districts(state,district) VALUES('Odisha','Kandhamal');
INSERT INTO districts(state,district) VALUES('Odisha','Kendrapara');
INSERT INTO districts(state,district) VALUES('Odisha','Kendujhar (Keonjhar)');
INSERT INTO districts(state,district) VALUES('Odisha','Khordha');
INSERT INTO districts(state,district) VALUES('Odisha','Koraput');
INSERT INTO districts(state,district) VALUES('Odisha','Malkangiri');
INSERT INTO districts(state,district) VALUES('Odisha','Mayurbhanj');
INSERT INTO districts(state,district) VALUES('Odisha','Nabarangpur');
INSERT INTO districts(state,district) VALUES('Odisha','Nayagarh');
INSERT INTO districts(state,district) VALUES('Odisha','Nuapada');
INSERT INTO districts(state,district) VALUES('Odisha','Puri');
INSERT INTO districts(state,district) VALUES('Odisha','Rayagada');
INSERT INTO districts(state,district) VALUES('Odisha','Sambalpur');
INSERT INTO districts(state,district) VALUES('Odisha','Sonepur');
INSERT INTO districts(state,district) VALUES('Odisha','Sundargarh');
INSERT INTO districts(state,district) VALUES('Puducherry (UT)','Karaikal');
INSERT INTO districts(state,district) VALUES('Puducherry (UT)','Mahe');
INSERT INTO districts(state,district) VALUES('Puducherry (UT)','Pondicherry');
INSERT INTO districts(state,district) VALUES('Puducherry (UT)','Yanam');
INSERT INTO districts(state,district) VALUES('Punjab','Amritsar');
INSERT INTO districts(state,district) VALUES('Punjab','Barnala');
INSERT INTO districts(state,district) VALUES('Punjab','Bathinda');
INSERT INTO districts(state,district) VALUES('Punjab','Faridkot');
INSERT INTO districts(state,district) VALUES('Punjab','Fatehgarh Sahib');
INSERT INTO districts(state,district) VALUES('Punjab','Fazilka');
INSERT INTO districts(state,district) VALUES('Punjab','Ferozepur');
INSERT INTO districts(state,district) VALUES('Punjab','Gurdaspur');
INSERT INTO districts(state,district) VALUES('Punjab','Hoshiarpur');
INSERT INTO districts(state,district) VALUES('Punjab','Jalandhar');
INSERT INTO districts(state,district) VALUES('Punjab','Kapurthala');
INSERT INTO districts(state,district) VALUES('Punjab','Ludhiana');
INSERT INTO districts(state,district) VALUES('Punjab','Mansa');
INSERT INTO districts(state,district) VALUES('Punjab','Moga');
INSERT INTO districts(state,district) VALUES('Punjab','Muktsar');
INSERT INTO districts(state,district) VALUES('Punjab','Nawanshahr (Shahid Bhagat Singh Nagar)');
INSERT INTO districts(state,district) VALUES('Punjab','Pathankot');
INSERT INTO districts(state,district) VALUES('Punjab','Patiala');
INSERT INTO districts(state,district) VALUES('Punjab','Rupnagar');
INSERT INTO districts(state,district) VALUES('Punjab','Sahibzada Ajit Singh Nagar (Mohali)');
INSERT INTO districts(state,district) VALUES('Punjab','Sangrur');
INSERT INTO districts(state,district) VALUES('Punjab','Tarn Taran');
INSERT INTO districts(state,district) VALUES('Rajasthan','Ajmer');
INSERT INTO districts(state,district) VALUES('Rajasthan','Alwar');
INSERT INTO districts(state,district) VALUES('Rajasthan','Banswara');
INSERT INTO districts(state,district) VALUES('Rajasthan','Baran');
INSERT INTO districts(state,district) VALUES('Rajasthan','Barmer');
INSERT INTO districts(state,district) VALUES('Rajasthan','Bharatpur');
INSERT INTO districts(state,district) VALUES('Rajasthan','Bhilwara');
INSERT INTO districts(state,district) VALUES('Rajasthan','Bikaner');
INSERT INTO districts(state,district) VALUES('Rajasthan','Bundi');
INSERT INTO districts(state,district) VALUES('Rajasthan','Chittorgarh');
INSERT INTO districts(state,district) VALUES('Rajasthan','Churu');
INSERT INTO districts(state,district) VALUES('Rajasthan','Dausa');
INSERT INTO districts(state,district) VALUES('Rajasthan','Dholpur');
INSERT INTO districts(state,district) VALUES('Rajasthan','Dungarpur');
INSERT INTO districts(state,district) VALUES('Rajasthan','Hanumangarh');
INSERT INTO districts(state,district) VALUES('Rajasthan','Jaipur');
INSERT INTO districts(state,district) VALUES('Rajasthan','Jaisalmer');
INSERT INTO districts(state,district) VALUES('Rajasthan','Jalore');
INSERT INTO districts(state,district) VALUES('Rajasthan','Jhalawar');
INSERT INTO districts(state,district) VALUES('Rajasthan','Jhunjhunu');
INSERT INTO districts(state,district) VALUES('Rajasthan','Jodhpur');
INSERT INTO districts(state,district) VALUES('Rajasthan','Karauli');
INSERT INTO districts(state,district) VALUES('Rajasthan','Kota');
INSERT INTO districts(state,district) VALUES('Rajasthan','Nagaur');
INSERT INTO districts(state,district) VALUES('Rajasthan','Pali');
INSERT INTO districts(state,district) VALUES('Rajasthan','Pratapgarh');
INSERT INTO districts(state,district) VALUES('Rajasthan','Rajsamand');
INSERT INTO districts(state,district) VALUES('Rajasthan','Sawai Madhopur');
INSERT INTO districts(state,district) VALUES('Rajasthan','Sikar');
INSERT INTO districts(state,district) VALUES('Rajasthan','Sirohi');
INSERT INTO districts(state,district) VALUES('Rajasthan','Sri Ganganagar');
INSERT INTO districts(state,district) VALUES('Rajasthan','Tonk');
INSERT INTO districts(state,district) VALUES('Rajasthan','Udaipur');
INSERT INTO districts(state,district) VALUES('Sikkim','East Sikkim');
INSERT INTO districts(state,district) VALUES('Sikkim','North Sikkim');
INSERT INTO districts(state,district) VALUES('Sikkim','South Sikkim');
INSERT INTO districts(state,district) VALUES('Sikkim','West Sikkim');
INSERT INTO districts(state,district) VALUES('Tamil Nadu','Ariyalur');
INSERT INTO districts(state,district) VALUES('Tamil Nadu','Chennai');
INSERT INTO districts(state,district) VALUES('Tamil Nadu','Coimbatore');
INSERT INTO districts(state,district) VALUES('Tamil Nadu','Cuddalore');
INSERT INTO districts(state,district) VALUES('Tamil Nadu','Dharmapuri');
INSERT INTO districts(state,district) VALUES('Tamil Nadu','Dindigul');
INSERT INTO districts(state,district) VALUES('Tamil Nadu','Erode');
INSERT INTO districts(state,district) VALUES('Tamil Nadu','Kanchipuram');
INSERT INTO districts(state,district) VALUES('Tamil Nadu','Kanyakumari');
INSERT INTO districts(state,district) VALUES('Tamil Nadu','Karur');
INSERT INTO districts(state,district) VALUES('Tamil Nadu','Krishnagiri');
INSERT INTO districts(state,district) VALUES('Tamil Nadu','Madurai');
INSERT INTO districts(state,district) VALUES('Tamil Nadu','Nagapattinam');
INSERT INTO districts(state,district) VALUES('Tamil Nadu','Namakkal');
INSERT INTO districts(state,district) VALUES('Tamil Nadu','Nilgiris');
INSERT INTO districts(state,district) VALUES('Tamil Nadu','Perambalur');
INSERT INTO districts(state,district) VALUES('Tamil Nadu','Pudukkottai');
INSERT INTO districts(state,district) VALUES('Tamil Nadu','Ramanathapuram');
INSERT INTO districts(state,district) VALUES('Tamil Nadu','Salem');
INSERT INTO districts(state,district) VALUES('Tamil Nadu','Sivaganga');
INSERT INTO districts(state,district) VALUES('Tamil Nadu','Thanjavur');
INSERT INTO districts(state,district) VALUES('Tamil Nadu','Theni');
INSERT INTO districts(state,district) VALUES('Tamil Nadu','Thoothukudi (Tuticorin)');
INSERT INTO districts(state,district) VALUES('Tamil Nadu','Tiruchirappalli');
INSERT INTO districts(state,district) VALUES('Tamil Nadu','Tirunelveli');
INSERT INTO districts(state,district) VALUES('Tamil Nadu','Tiruppur');
INSERT INTO districts(state,district) VALUES('Tamil Nadu','Tiruvallur');
INSERT INTO districts(state,district) VALUES('Tamil Nadu','Tiruvannamalai');
INSERT INTO districts(state,district) VALUES('Tamil Nadu','Tiruvarur');
INSERT INTO districts(state,district) VALUES('Tamil Nadu','Vellore');
INSERT INTO districts(state,district) VALUES('Tamil Nadu','Viluppuram');
INSERT INTO districts(state,district) VALUES('Tamil Nadu','Virudhunagar');
INSERT INTO districts(state,district) VALUES('Telangana','Adilabad');
INSERT INTO districts(state,district) VALUES('Telangana','Bhadradri Kothagudem');
INSERT INTO districts(state,district) VALUES('Telangana','Hyderabad');
INSERT INTO districts(state,district) VALUES('Telangana','Jagtial');
INSERT INTO districts(state,district) VALUES('Telangana','Jangaon');
INSERT INTO districts(state,district) VALUES('Telangana','Jayashankar Bhoopalpally');
INSERT INTO districts(state,district) VALUES('Telangana','Jogulamba Gadwal');
INSERT INTO districts(state,district) VALUES('Telangana','Kamareddy');
INSERT INTO districts(state,district) VALUES('Telangana','Karimnagar');
INSERT INTO districts(state,district) VALUES('Telangana','Khammam');
INSERT INTO districts(state,district) VALUES('Telangana','Komaram Bheem Asifabad');
INSERT INTO districts(state,district) VALUES('Telangana','Mahabubabad');
INSERT INTO districts(state,district) VALUES('Telangana','Mahabubnagar');
INSERT INTO districts(state,district) VALUES('Telangana','Mancherial');
INSERT INTO districts(state,district) VALUES('Telangana','Medak');
INSERT INTO districts(state,district) VALUES('Telangana','Medchal');
INSERT INTO districts(state,district) VALUES('Telangana','Nagarkurnool');
INSERT INTO districts(state,district) VALUES('Telangana','Nalgonda');
INSERT INTO districts(state,district) VALUES('Telangana','Nirmal');
INSERT INTO districts(state,district) VALUES('Telangana','Nizamabad');
INSERT INTO districts(state,district) VALUES('Telangana','Peddapalli');
INSERT INTO districts(state,district) VALUES('Telangana','Rajanna Sircilla');
INSERT INTO districts(state,district) VALUES('Telangana','Rangareddy');
INSERT INTO districts(state,district) VALUES('Telangana','Sangareddy');
INSERT INTO districts(state,district) VALUES('Telangana','Siddipet');
INSERT INTO districts(state,district) VALUES('Telangana','Suryapet');
INSERT INTO districts(state,district) VALUES('Telangana','Vikarabad');
INSERT INTO districts(state,district) VALUES('Telangana','Wanaparthy');
INSERT INTO districts(state,district) VALUES('Telangana','Warangal (Rural)');
INSERT INTO districts(state,district) VALUES('Telangana','Warangal (Urban)');
INSERT INTO districts(state,district) VALUES('Telangana','Yadadri Bhuvanagiri');
INSERT INTO districts(state,district) VALUES('Tripura','Dhalai');
INSERT INTO districts(state,district) VALUES('Tripura','Gomati');
INSERT INTO districts(state,district) VALUES('Tripura','Khowai');
INSERT INTO districts(state,district) VALUES('Tripura','North Tripura');
INSERT INTO districts(state,district) VALUES('Tripura','Sepahijala');
INSERT INTO districts(state,district) VALUES('Tripura','South Tripura');
INSERT INTO districts(state,district) VALUES('Tripura','Unakoti');
INSERT INTO districts(state,district) VALUES('Tripura','West Tripura');
INSERT INTO districts(state,district) VALUES('Uttarakhand','Almora');
INSERT INTO districts(state,district) VALUES('Uttarakhand','Bageshwar');
INSERT INTO districts(state,district) VALUES('Uttarakhand','Chamoli');
INSERT INTO districts(state,district) VALUES('Uttarakhand','Champawat');
INSERT INTO districts(state,district) VALUES('Uttarakhand','Dehradun');
INSERT INTO districts(state,district) VALUES('Uttarakhand','Haridwar');
INSERT INTO districts(state,district) VALUES('Uttarakhand','Nainital');
INSERT INTO districts(state,district) VALUES('Uttarakhand','Pauri Garhwal');
INSERT INTO districts(state,district) VALUES('Uttarakhand','Pithoragarh');
INSERT INTO districts(state,district) VALUES('Uttarakhand','Rudraprayag');
INSERT INTO districts(state,district) VALUES('Uttarakhand','Tehri Garhwal');
INSERT INTO districts(state,district) VALUES('Uttarakhand','Udham Singh Nagar');
INSERT INTO districts(state,district) VALUES('Uttarakhand','Uttarkashi');
INSERT INTO districts(state,district) VALUES('Uttar Pradesh','Agra');
INSERT INTO districts(state,district) VALUES('Uttar Pradesh','Aligarh');
INSERT INTO districts(state,district) VALUES('Uttar Pradesh','Allahabad');
INSERT INTO districts(state,district) VALUES('Uttar Pradesh','Ambedkar Nagar');
INSERT INTO districts(state,district) VALUES('Uttar Pradesh','Amethi (Chatrapati Sahuji Mahraj Nagar)');
INSERT INTO districts(state,district) VALUES('Uttar Pradesh','Amroha (J.P. Nagar)');
INSERT INTO districts(state,district) VALUES('Uttar Pradesh','Auraiya');
INSERT INTO districts(state,district) VALUES('Uttar Pradesh','Azamgarh');
INSERT INTO districts(state,district) VALUES('Uttar Pradesh','Baghpat');
INSERT INTO districts(state,district) VALUES('Uttar Pradesh','Bahraich');
INSERT INTO districts(state,district) VALUES('Uttar Pradesh','Ballia');
INSERT INTO districts(state,district) VALUES('Uttar Pradesh','Balrampur');
INSERT INTO districts(state,district) VALUES('Uttar Pradesh','Banda');
INSERT INTO districts(state,district) VALUES('Uttar Pradesh','Barabanki');
INSERT INTO districts(state,district) VALUES('Uttar Pradesh','Bareilly');
INSERT INTO districts(state,district) VALUES('Uttar Pradesh','Basti');
INSERT INTO districts(state,district) VALUES('Uttar Pradesh','Bhadohi');
INSERT INTO districts(state,district) VALUES('Uttar Pradesh','Bijnor');
INSERT INTO districts(state,district) VALUES('Uttar Pradesh','Budaun');
INSERT INTO districts(state,district) VALUES('Uttar Pradesh','Bulandshahr');
INSERT INTO districts(state,district) VALUES('Uttar Pradesh','Chandauli');
INSERT INTO districts(state,district) VALUES('Uttar Pradesh','Chitrakoot');
INSERT INTO districts(state,district) VALUES('Uttar Pradesh','Deoria');
INSERT INTO districts(state,district) VALUES('Uttar Pradesh','Etah');
INSERT INTO districts(state,district) VALUES('Uttar Pradesh','Etawah');
INSERT INTO districts(state,district) VALUES('Uttar Pradesh','Faizabad');
INSERT INTO districts(state,district) VALUES('Uttar Pradesh','Farrukhabad');
INSERT INTO districts(state,district) VALUES('Uttar Pradesh','Fatehpur');
INSERT INTO districts(state,district) VALUES('Uttar Pradesh','Firozabad');
INSERT INTO districts(state,district) VALUES('Uttar Pradesh','Gautam Buddha Nagar');
INSERT INTO districts(state,district) VALUES('Uttar Pradesh','Ghaziabad');
INSERT INTO districts(state,district) VALUES('Uttar Pradesh','Ghazipur');
INSERT INTO districts(state,district) VALUES('Uttar Pradesh','Gonda');
INSERT INTO districts(state,district) VALUES('Uttar Pradesh','Gorakhpur');
INSERT INTO districts(state,district) VALUES('Uttar Pradesh','Hamirpur');
INSERT INTO districts(state,district) VALUES('Uttar Pradesh','Hapur (Panchsheel Nagar)');
INSERT INTO districts(state,district) VALUES('Uttar Pradesh','Hardoi');
INSERT INTO districts(state,district) VALUES('Uttar Pradesh','Hathras');
INSERT INTO districts(state,district) VALUES('Uttar Pradesh','Jalaun');
INSERT INTO districts(state,district) VALUES('Uttar Pradesh','Jaunpur');
INSERT INTO districts(state,district) VALUES('Uttar Pradesh','Jhansi');
INSERT INTO districts(state,district) VALUES('Uttar Pradesh','Kannauj');
INSERT INTO districts(state,district) VALUES('Uttar Pradesh','Kanpur Dehat');
INSERT INTO districts(state,district) VALUES('Uttar Pradesh','Kanpur Nagar');
INSERT INTO districts(state,district) VALUES('Uttar Pradesh','Kanshiram Nagar (Kasganj)');
INSERT INTO districts(state,district) VALUES('Uttar Pradesh','Kaushambi');
INSERT INTO districts(state,district) VALUES('Uttar Pradesh','Kushinagar (Padrauna)');
INSERT INTO districts(state,district) VALUES('Uttar Pradesh','Lakhimpur - Kheri');
INSERT INTO districts(state,district) VALUES('Uttar Pradesh','Lalitpur');
INSERT INTO districts(state,district) VALUES('Uttar Pradesh','Lucknow');
INSERT INTO districts(state,district) VALUES('Uttar Pradesh','Maharajganj');
INSERT INTO districts(state,district) VALUES('Uttar Pradesh','Mahoba');
INSERT INTO districts(state,district) VALUES('Uttar Pradesh','Mainpuri');
INSERT INTO districts(state,district) VALUES('Uttar Pradesh','Mathura');
INSERT INTO districts(state,district) VALUES('Uttar Pradesh','Mau');
INSERT INTO districts(state,district) VALUES('Uttar Pradesh','Meerut');
INSERT INTO districts(state,district) VALUES('Uttar Pradesh','Mirzapur');
INSERT INTO districts(state,district) VALUES('Uttar Pradesh','Moradabad');
INSERT INTO districts(state,district) VALUES('Uttar Pradesh','Muzaffarnagar');
INSERT INTO districts(state,district) VALUES('Uttar Pradesh','Pilibhit');
INSERT INTO districts(state,district) VALUES('Uttar Pradesh','Pratapgarh');
INSERT INTO districts(state,district) VALUES('Uttar Pradesh','RaeBareli');
INSERT INTO districts(state,district) VALUES('Uttar Pradesh','Rampur');
INSERT INTO districts(state,district) VALUES('Uttar Pradesh','Saharanpur');
INSERT INTO districts(state,district) VALUES('Uttar Pradesh','Sambhal (Bhim Nagar)');
INSERT INTO districts(state,district) VALUES('Uttar Pradesh','Sant Kabir Nagar');
INSERT INTO districts(state,district) VALUES('Uttar Pradesh','Shahjahanpur');
INSERT INTO districts(state,district) VALUES('Uttar Pradesh','Shamali (Prabuddh Nagar)');
INSERT INTO districts(state,district) VALUES('Uttar Pradesh','Shravasti');
INSERT INTO districts(state,district) VALUES('Uttar Pradesh','Siddharth Nagar');
INSERT INTO districts(state,district) VALUES('Uttar Pradesh','Sitapur');
INSERT INTO districts(state,district) VALUES('Uttar Pradesh','Sonbhadra');
INSERT INTO districts(state,district) VALUES('Uttar Pradesh','Sultanpur');
INSERT INTO districts(state,district) VALUES('Uttar Pradesh','Unnao');
INSERT INTO districts(state,district) VALUES('Uttar Pradesh','Varanasi');
INSERT INTO districts(state,district) VALUES('West Bengal','Alipurduar');
INSERT INTO districts(state,district) VALUES('West Bengal','Bankura');
INSERT INTO districts(state,district) VALUES('West Bengal','Birbhum');
INSERT INTO districts(state,district) VALUES('West Bengal','Burdwan (Bardhaman)');
INSERT INTO districts(state,district) VALUES('West Bengal','Cooch Behar');
INSERT INTO districts(state,district) VALUES('West Bengal','Dakshin Dinajpur (South Dinajpur)');
INSERT INTO districts(state,district) VALUES('West Bengal','Darjeeling');
INSERT INTO districts(state,district) VALUES('West Bengal','Hooghly');
INSERT INTO districts(state,district) VALUES('West Bengal','Howrah');
INSERT INTO districts(state,district) VALUES('West Bengal','Jalpaiguri');
INSERT INTO districts(state,district) VALUES('West Bengal','Kalimpong');
INSERT INTO districts(state,district) VALUES('West Bengal','Kolkata');
INSERT INTO districts(state,district) VALUES('West Bengal','Malda');
INSERT INTO districts(state,district) VALUES('West Bengal','Murshidabad');
INSERT INTO districts(state,district) VALUES('West Bengal','Nadia');
INSERT INTO districts(state,district) VALUES('West Bengal','North 24 Parganas');
INSERT INTO districts(state,district) VALUES('West Bengal','Paschim Medinipur (West Medinipur)');
INSERT INTO districts(state,district) VALUES('West Bengal','Purba Medinipur (East Medinipur)');
INSERT INTO districts(state,district) VALUES('West Bengal','Purulia');
INSERT INTO districts(state,district) VALUES('West Bengal','South 24 Parganas');
INSERT INTO districts(state,district) VALUES('West Bengal','Uttar Dinajpur (North Dinajpur)');
