INSERT INTO states(name) values('Andhra Pradesh');
INSERT INTO states(name) values('Arunachal Pradesh');
INSERT INTO states(name) values('Assam');
INSERT INTO states(name) values('Bihar');
INSERT INTO states(name) values('Chhattisgarh');
INSERT INTO states(name) values('Goa');
INSERT INTO states(name) values('Gujarat');
INSERT INTO states(name) values('Haryana');
INSERT INTO states(name) values('Himachal Pradesh');
INSERT INTO states(name) values('Jammu and Kashmir');
INSERT INTO states(name) values('Jharkhand');
INSERT INTO states(name) values('Karnataka');
INSERT INTO states(name) values('Kerala');
INSERT INTO states(name) values('Madhya Pradesh');
INSERT INTO states(name) values('Maharashtra');
INSERT INTO states(name) values('Manipur');
INSERT INTO states(name) values('Meghalaya');
INSERT INTO states(name) values('Mizoram');
INSERT INTO states(name) values('Nagaland');
INSERT INTO states(name) values('Odisha');
INSERT INTO states(name) values('Punjab');
INSERT INTO states(name) values('Rajasthan');
INSERT INTO states(name) values('Sikkim');
INSERT INTO states(name) values('Tamil Nadu');
INSERT INTO states(name) values('Telangana');
INSERT INTO states(name) values('Tripura');
INSERT INTO states(name) values('Uttar Pradesh');
INSERT INTO states(name) values('Uttarakhand');
INSERT INTO states(name) values('West Bengal');